"use client"
import { use } from "react"
import PageLayout from "@/components/page-layout"
import Link from "next/link"
import { useLanguage } from "@/lib/language-context"

const categoryProducts: Record<string, any[]> = {
  vegetables: [
    {
      id: "v1",
      name: "Fresh Tomato",
      price: 40,
      image: "/fresh-red-tomato.jpg",
      category: "Vegetables",
      rating: 4.5,
      description: "Freshly picked red tomatoes",
    },
    {
      id: "v2",
      name: "Golden Onion",
      price: 35,
      image: "/golden-onion.jpg",
      category: "Vegetables",
      rating: 4.3,
      description: "Sweet and fragrant onions",
    },
    {
      id: "v3",
      name: "Fresh Spinach",
      price: 30,
      image: "/fresh-green-spinach.jpg",
      category: "Vegetables",
      rating: 4.7,
      description: "Organic green spinach",
    },
    {
      id: "v4",
      name: "Orange Carrot",
      price: 45,
      image: "/orange-carrot.png",
      category: "Vegetables",
      rating: 4.6,
      description: "Crunchy and sweet carrots",
    },
    {
      id: "v5",
      name: "Green Capsicum",
      price: 60,
      image: "/fresh-green-capsicum.jpg",
      category: "Vegetables",
      rating: 4.4,
      description: "Fresh green bell peppers",
    },
    {
      id: "v6",
      name: "Fresh Garlic",
      price: 50,
      image: "/fresh-garlic-bulbs.jpg",
      category: "Vegetables",
      rating: 4.5,
      description: "Aromatic garlic bulbs",
    },
    {
      id: "v7",
      name: "Green Beans",
      price: 55,
      image: "/fresh-organic-vegetables.png",
      category: "Vegetables",
      rating: 4.6,
      description: "Crisp green beans",
    },
    {
      id: "v8",
      name: "Cauliflower",
      price: 50,
      image: "/fresh-organic-vegetables.png",
      category: "Vegetables",
      rating: 4.5,
      description: "Fresh white cauliflower",
    },
    {
      id: "v9",
      name: "Broccoli",
      price: 70,
      image: "/fresh-organic-vegetables.png",
      category: "Vegetables",
      rating: 4.7,
      description: "Nutritious broccoli florets",
    },
    {
      id: "v10",
      name: "Potato",
      price: 40,
      image: "/fresh-organic-vegetables.png",
      category: "Vegetables",
      rating: 4.4,
      description: "Fresh potatoes",
    },
  ],
  fruits: [
    {
      id: "f1",
      name: "Fresh Red Apple",
      price: 80,
      image: "/fresh-red-apple.png",
      category: "Fruits",
      rating: 4.8,
      description: "Crispy red apples",
    },
    {
      id: "f2",
      name: "Yellow Bananas",
      price: 50,
      image: "/yellow-banana-bunch.png",
      category: "Fruits",
      rating: 4.6,
      description: "Ripe yellow bananas",
    },
    {
      id: "f3",
      name: "Orange",
      price: 60,
      image: "/images/orange.png",
      category: "Fruits",
      rating: 4.5,
      description: "Juicy oranges",
    },
    {
      id: "f4",
      name: "Ripe Mango",
      price: 100,
      image: "/ripe-mango-fruit.jpg",
      category: "Fruits",
      rating: 4.9,
      description: "Sweet mango perfection",
    },
    {
      id: "f5",
      name: "Fresh Grapes",
      price: 90,
      image: "/assorted-fresh-fruits.jpg",
      category: "Fruits",
      rating: 4.7,
      description: "Sweet green grapes",
    },
    {
      id: "f6",
      name: "Watermelon",
      price: 70,
      image: "/assorted-fresh-fruits.jpg",
      category: "Fruits",
      rating: 4.6,
      description: "Juicy watermelon",
    },
    {
      id: "f7",
      name: "Pomegranate",
      price: 120,
      image: "/assorted-fresh-fruits.jpg",
      category: "Fruits",
      rating: 4.8,
      description: "Fresh pomegranate",
    },
    {
      id: "f8",
      name: "Papaya",
      price: 55,
      image: "/assorted-fresh-fruits.jpg",
      category: "Fruits",
      rating: 4.5,
      description: "Ripe papaya",
    },
    {
      id: "f9",
      name: "Guava",
      price: 45,
      image: "/assorted-fresh-fruits.jpg",
      category: "Fruits",
      rating: 4.6,
      description: "Fresh guava",
    },
    {
      id: "f10",
      name: "Pineapple",
      price: 85,
      image: "/assorted-fresh-fruits.jpg",
      category: "Fruits",
      rating: 4.7,
      description: "Sweet pineapple",
    },
  ],
  spices: [
    {
      id: "s1",
      name: "Turmeric Powder",
      price: 120,
      image: "/turmeric-powder.png",
      category: "Spices",
      rating: 4.7,
      description: "Pure turmeric powder",
    },
    {
      id: "s2",
      name: "Cumin Seeds",
      price: 150,
      image: "/cumin-seeds-spice.jpg",
      category: "Spices",
      rating: 4.6,
      description: "Aromatic cumin seeds",
    },
    {
      id: "s3",
      name: "Chili Powder",
      price: 100,
      image: "/red-chili-powder.jpg",
      category: "Spices",
      rating: 4.8,
      description: "Red chili powder",
    },
    {
      id: "s4",
      name: "Coriander",
      price: 130,
      image: "/coriander-powder.jpg",
      category: "Spices",
      rating: 4.5,
      description: "Fresh coriander powder",
    },
    {
      id: "s5",
      name: "Garam Masala",
      price: 180,
      image: "/indian-spices-turmeric-cumin-cinnamon.jpg",
      category: "Spices",
      rating: 4.9,
      description: "Aromatic garam masala",
    },
    {
      id: "s6",
      name: "Black Pepper",
      price: 140,
      image: "/indian-spices-colorful-arrangement.jpg",
      category: "Spices",
      rating: 4.6,
      description: "Whole black pepper",
    },
    {
      id: "s7",
      name: "Cardamom",
      price: 200,
      image: "/indian-spices-colorful-arrangement.jpg",
      category: "Spices",
      rating: 4.8,
      description: "Green cardamom pods",
    },
    {
      id: "s8",
      name: "Cinnamon",
      price: 160,
      image: "/indian-spices-turmeric-cumin-cinnamon.jpg",
      category: "Spices",
      rating: 4.7,
      description: "Cinnamon sticks",
    },
    {
      id: "s9",
      name: "Fenugreek Seeds",
      price: 110,
      image: "/indian-spices-colorful-arrangement.jpg",
      category: "Spices",
      rating: 4.5,
      description: "Fenugreek seeds",
    },
    {
      id: "s10",
      name: "Mustard Seeds",
      price: 90,
      image: "/indian-spices-colorful-arrangement.jpg",
      category: "Spices",
      rating: 4.6,
      description: "Yellow mustard seeds",
    },
  ],
  dairy: [
    {
      id: "d1",
      name: "Fresh Milk",
      price: 65,
      image: "/fresh-milk-carton.jpg",
      category: "Dairy",
      rating: 4.7,
      description: "Pure fresh milk",
    },
    {
      id: "d2",
      name: "Yogurt",
      price: 50,
      image: "/yogurt-container.jpg",
      category: "Dairy",
      rating: 4.6,
      description: "Creamy yogurt",
    },
    {
      id: "d3",
      name: "Cheese Block",
      price: 250,
      image: "/cheese-block.png",
      category: "Dairy",
      rating: 4.8,
      description: "Premium cheese",
    },
    {
      id: "d4",
      name: "Butter",
      price: 180,
      image: "/butter-pack.jpg",
      category: "Dairy",
      rating: 4.5,
      description: "Creamy butter",
    },
    {
      id: "d5",
      name: "Paneer",
      price: 200,
      image: "/fresh-milk-carton.jpg",
      category: "Dairy",
      rating: 4.7,
      description: "Fresh paneer",
    },
    {
      id: "d6",
      name: "Cream",
      price: 120,
      image: "/fresh-milk-carton.jpg",
      category: "Dairy",
      rating: 4.6,
      description: "Fresh cream",
    },
    {
      id: "d7",
      name: "Ghee",
      price: 350,
      image: "/butter-pack.jpg",
      category: "Dairy",
      rating: 4.9,
      description: "Pure desi ghee",
    },
    {
      id: "d8",
      name: "Curd",
      price: 45,
      image: "/yogurt-container.jpg",
      category: "Dairy",
      rating: 4.6,
      description: "Fresh curd",
    },
    {
      id: "d9",
      name: "Mozzarella Cheese",
      price: 280,
      image: "/cheese-block.png",
      category: "Dairy",
      rating: 4.8,
      description: "Mozzarella cheese",
    },
    {
      id: "d10",
      name: "Cottage Cheese",
      price: 150,
      image: "/cheese-block.png",
      category: "Dairy",
      rating: 4.7,
      description: "Fresh cottage cheese",
    },
  ],
  beverages: [
    {
      id: "b1",
      name: "Orange Juice",
      price: 80,
      image: "/orange-juice-bottle.jpg",
      category: "Beverages",
      rating: 4.6,
      description: "Fresh orange juice",
    },
    {
      id: "b2",
      name: "Premium Tea",
      price: 200,
      image: "/premium-tea-leaves.jpg",
      category: "Beverages",
      rating: 4.8,
      description: "Premium tea leaves",
    },
    {
      id: "b3",
      name: "Coffee Beans",
      price: 250,
      image: "/coffee-beans-roasted.jpg",
      category: "Beverages",
      rating: 4.9,
      description: "Roasted coffee beans",
    },
    {
      id: "b4",
      name: "Mineral Water",
      price: 30,
      image: "/mineral-water-bottle.jpg",
      category: "Beverages",
      rating: 4.4,
      description: "Pure mineral water",
    },
    {
      id: "b5",
      name: "Apple Juice",
      price: 85,
      image: "/orange-juice-bottle.jpg",
      category: "Beverages",
      rating: 4.5,
      description: "Fresh apple juice",
    },
    {
      id: "b6",
      name: "Green Tea",
      price: 180,
      image: "/premium-tea-leaves.jpg",
      category: "Beverages",
      rating: 4.7,
      description: "Organic green tea",
    },
    {
      id: "b7",
      name: "Instant Coffee",
      price: 150,
      image: "/coffee-beans-roasted.jpg",
      category: "Beverages",
      rating: 4.6,
      description: "Instant coffee powder",
    },
    {
      id: "b8",
      name: "Coconut Water",
      price: 40,
      image: "/mineral-water-bottle.jpg",
      category: "Beverages",
      rating: 4.8,
      description: "Fresh coconut water",
    },
    {
      id: "b9",
      name: "Lemonade",
      price: 45,
      image: "/orange-juice-bottle.jpg",
      category: "Beverages",
      rating: 4.5,
      description: "Fresh lemonade",
    },
    {
      id: "b10",
      name: "Herbal Tea",
      price: 220,
      image: "/premium-tea-leaves.jpg",
      category: "Beverages",
      rating: 4.7,
      description: "Herbal tea blend",
    },
  ],
  "dry-fruits": [
    {
      id: "df1",
      name: "California Almonds",
      price: 500,
      image: "/california-almonds-nuts.jpg",
      category: "Dry Fruits",
      rating: 4.9,
      description: "Premium almonds",
    },
    {
      id: "df2",
      name: "Cashew Nuts",
      price: 450,
      image: "/cashew-nuts-roasted.jpg",
      category: "Dry Fruits",
      rating: 4.8,
      description: "Roasted cashews",
    },
    {
      id: "df3",
      name: "Black Raisins",
      price: 200,
      image: "/black-raisins-dried.jpg",
      category: "Dry Fruits",
      rating: 4.6,
      description: "Dried raisins",
    },
    {
      id: "df4",
      name: "Premium Dates",
      price: 300,
      image: "/premium-dates-fruit.jpg",
      category: "Dry Fruits",
      rating: 4.7,
      description: "Premium dates",
    },
    {
      id: "df5",
      name: "Walnuts",
      price: 550,
      image: "/dry-fruits-almonds-cashews-raisins.jpg",
      category: "Dry Fruits",
      rating: 4.8,
      description: "Premium walnuts",
    },
    {
      id: "df6",
      name: "Pistachios",
      price: 600,
      image: "/dry-fruits-almonds-cashews-raisins.jpg",
      category: "Dry Fruits",
      rating: 4.9,
      description: "Green pistachios",
    },
    {
      id: "df7",
      name: "Apricots",
      price: 350,
      image: "/black-raisins-dried.jpg",
      category: "Dry Fruits",
      rating: 4.7,
      description: "Dried apricots",
    },
    {
      id: "df8",
      name: "Figs",
      price: 400,
      image: "/premium-dates-fruit.jpg",
      category: "Dry Fruits",
      rating: 4.6,
      description: "Dried figs",
    },
    {
      id: "df9",
      name: "Hazelnuts",
      price: 520,
      image: "/california-almonds-nuts.jpg",
      category: "Dry Fruits",
      rating: 4.8,
      description: "Roasted hazelnuts",
    },
    {
      id: "df10",
      name: "Prunes",
      price: 280,
      image: "/black-raisins-dried.jpg",
      category: "Dry Fruits",
      rating: 4.5,
      description: "Dried prunes",
    },
  ],
  chips: [
    {
      id: "c1",
      name: "Potato Chips",
      price: 40,
      image: "/crispy-potato-chips.jpg",
      category: "Chips",
      rating: 4.5,
      description: "Crispy potato chips",
    },
    {
      id: "c2",
      name: "Corn Chips",
      price: 45,
      image: "/roasted-corn-chips.jpg",
      category: "Chips",
      rating: 4.6,
      description: "Roasted corn chips",
    },
    {
      id: "c3",
      name: "Prawn Chips",
      price: 80,
      image: "/spicy-prawn-chips.jpg",
      category: "Chips",
      rating: 4.7,
      description: "Spicy prawn chips",
    },
    {
      id: "c4",
      name: "Vegetable Chips",
      price: 50,
      image: "/healthy-vegetable-chips.jpg",
      category: "Chips",
      rating: 4.8,
      description: "Healthy vegetable chips",
    },
    {
      id: "c5",
      name: "Onion Rings",
      price: 55,
      image: "/crispy-potato-chips.jpg",
      category: "Chips",
      rating: 4.6,
      description: "Crispy onion rings",
    },
    {
      id: "c6",
      name: "Banana Chips",
      price: 60,
      image: "/roasted-corn-chips.jpg",
      category: "Chips",
      rating: 4.7,
      description: "Sweet banana chips",
    },
    {
      id: "c7",
      name: "Tortilla Chips",
      price: 48,
      image: "/roasted-corn-chips.jpg",
      category: "Chips",
      rating: 4.5,
      description: "Mexican tortilla chips",
    },
    {
      id: "c8",
      name: "Cheese Chips",
      price: 65,
      image: "/crispy-potato-chips.jpg",
      category: "Chips",
      rating: 4.8,
      description: "Cheesy chips",
    },
    {
      id: "c9",
      name: "Salt & Vinegar Chips",
      price: 42,
      image: "/crispy-potato-chips.jpg",
      category: "Chips",
      rating: 4.6,
      description: "Tangy salt & vinegar",
    },
    {
      id: "c10",
      name: "Barbecue Chips",
      price: 45,
      image: "/spicy-prawn-chips.jpg",
      category: "Chips",
      rating: 4.7,
      description: "Smoky barbecue flavor",
    },
  ],
  biscuits: [
    {
      id: "bi1",
      name: "Digestive Biscuits",
      price: 60,
      image: "/whole-wheat-digestive-biscuits.jpg",
      category: "Biscuits",
      rating: 4.6,
      description: "Whole wheat digestive",
    },
    {
      id: "bi2",
      name: "Marie Biscuits",
      price: 50,
      image: "/light-crispy-marie-biscuits.jpg",
      category: "Biscuits",
      rating: 4.5,
      description: "Light and crispy",
    },
    {
      id: "bi3",
      name: "Chocolate Biscuits",
      price: 70,
      image: "/chocolate-biscuits.jpg",
      category: "Biscuits",
      rating: 4.7,
      description: "Chocolate biscuits",
    },
    {
      id: "bi4",
      name: "Wafer Biscuits",
      price: 65,
      image: "/wafer-biscuits.jpg",
      category: "Biscuits",
      rating: 4.6,
      description: "Thin wafer biscuits",
    },
    {
      id: "bi5",
      name: "Butter Cookies",
      price: 75,
      image: "/chocolate-biscuits.jpg",
      category: "Biscuits",
      rating: 4.8,
      description: "Buttery cookies",
    },
    {
      id: "bi6",
      name: "Cream Biscuits",
      price: 68,
      image: "/whole-wheat-digestive-biscuits.jpg",
      category: "Biscuits",
      rating: 4.7,
      description: "Cream filled biscuits",
    },
    {
      id: "bi7",
      name: "Oreo Biscuits",
      price: 80,
      image: "/chocolate-biscuits.jpg",
      category: "Biscuits",
      rating: 4.9,
      description: "Chocolate cream cookies",
    },
    {
      id: "bi8",
      name: "Coconut Biscuits",
      price: 62,
      image: "/light-crispy-marie-biscuits.jpg",
      category: "Biscuits",
      rating: 4.6,
      description: "Coconut flavored",
    },
    {
      id: "bi9",
      name: "Glucose Biscuits",
      price: 45,
      image: "/whole-wheat-digestive-biscuits.jpg",
      category: "Biscuits",
      rating: 4.5,
      description: "Energy biscuits",
    },
    {
      id: "bi10",
      name: "Honey Biscuits",
      price: 58,
      image: "/wafer-biscuits.jpg",
      category: "Biscuits",
      rating: 4.7,
      description: "Honey sweetened",
    },
  ],
  soaps: [
    {
      id: "so1",
      name: "Natural Soap Bar",
      price: 80,
      image: "/natural-soap-bar.jpg",
      category: "Soaps",
      rating: 4.6,
      description: "Natural soap bar",
    },
    {
      id: "so2",
      name: "Herbal Shampoo",
      price: 150,
      image: "/herbal-shampoo.jpg",
      category: "Soaps",
      rating: 4.7,
      description: "Herbal shampoo",
    },
    {
      id: "so3",
      name: "Body Wash",
      price: 120,
      image: "/body-wash.jpg",
      category: "Soaps",
      rating: 4.5,
      description: "Gentle body wash",
    },
    {
      id: "so4",
      name: "Hand Wash",
      price: 100,
      image: "/hand-wash.jpg",
      category: "Soaps",
      rating: 4.8,
      description: "Antibacterial hand wash",
    },
    {
      id: "so5",
      name: "Face Wash",
      price: 130,
      image: "/natural-soap-bar.jpg",
      category: "Soaps",
      rating: 4.7,
      description: "Gentle face wash",
    },
    {
      id: "so6",
      name: "Conditioner",
      price: 140,
      image: "/herbal-shampoo.jpg",
      category: "Soaps",
      rating: 4.6,
      description: "Hair conditioner",
    },
    {
      id: "so7",
      name: "Liquid Soap",
      price: 90,
      image: "/hand-wash.jpg",
      category: "Soaps",
      rating: 4.5,
      description: "Liquid hand soap",
    },
    {
      id: "so8",
      name: "Shower Gel",
      price: 110,
      image: "/body-wash.jpg",
      category: "Soaps",
      rating: 4.6,
      description: "Refreshing shower gel",
    },
    {
      id: "so9",
      name: "Baby Soap",
      price: 70,
      image: "/natural-soap-bar.jpg",
      category: "Soaps",
      rating: 4.8,
      description: "Gentle baby soap",
    },
    {
      id: "so10",
      name: "Antiseptic Soap",
      price: 85,
      image: "/natural-soap-bar.jpg",
      category: "Soaps",
      rating: 4.7,
      description: "Antiseptic soap bar",
    },
  ],
  namkeen: [
    {
      id: "n1",
      name: "Bhujia",
      price: 60,
      image: "/bhujia-snack.jpg",
      category: "Namkeen",
      rating: 4.7,
      description: "Spicy bhujia",
    },
    {
      id: "n2",
      name: "Mathri",
      price: 70,
      image: "/mathri-snack.jpg",
      category: "Namkeen",
      rating: 4.6,
      description: "Crispy mathri",
    },
    {
      id: "n3",
      name: "Chakli",
      price: 80,
      image: "/chakli-snack.jpg",
      category: "Namkeen",
      rating: 4.8,
      description: "Twisted chakli",
    },
    {
      id: "n4",
      name: "Sev",
      price: 65,
      image: "/sev-snack.jpg",
      category: "Namkeen",
      rating: 4.5,
      description: "Delicious sev",
    },
    {
      id: "n5",
      name: "Namkeen Mix",
      price: 75,
      image: "/indian-namkeen-snacks-mix.jpg",
      category: "Namkeen",
      rating: 4.8,
      description: "Mixed namkeen",
    },
    {
      id: "n6",
      name: "Kachori",
      price: 85,
      image: "/mathri-snack.jpg",
      category: "Namkeen",
      rating: 4.7,
      description: "Spicy kachori",
    },
    {
      id: "n7",
      name: "Farsan",
      price: 68,
      image: "/indian-namkeen-snacks-mix.jpg",
      category: "Namkeen",
      rating: 4.6,
      description: "Gujarati farsan",
    },
    {
      id: "n8",
      name: "Mixture",
      price: 72,
      image: "/indian-namkeen-snacks-mix.jpg",
      category: "Namkeen",
      rating: 4.7,
      description: "Crispy mixture",
    },
    {
      id: "n9",
      name: "Khatta Meetha",
      price: 78,
      image: "/bhujia-snack.jpg",
      category: "Namkeen",
      rating: 4.8,
      description: "Sweet and sour",
    },
    {
      id: "n10",
      name: "Masala Peanuts",
      price: 55,
      image: "/indian-namkeen-snacks-mix.jpg",
      category: "Namkeen",
      rating: 4.6,
      description: "Spicy peanuts",
    },
  ],
}

export default function CategoryPage({ params }: { params: Promise<{ slug: string }> }) {
  const { t } = useLanguage()
  const { slug } = use(params)
  const products = categoryProducts[slug] || []
  const categoryName = products[0]?.category || slug

  const categoryTranslations: Record<string, string> = {
    Vegetables: t("cat.vegetables"),
    Fruits: t("cat.fruits"),
    Spices: t("cat.spices"),
    Dairy: t("cat.dairy"),
    Beverages: t("cat.beverages"),
    "Dry Fruits": t("cat.dryfruits"),
    Chips: t("cat.chips"),
    Biscuits: t("cat.biscuits"),
    Soaps: t("cat.soaps"),
    Namkeen: t("cat.namkeen"),
  }

  const translatedCategoryName = categoryTranslations[categoryName] || categoryName

  const productNameMap: Record<string, string> = {
    // Vegetables
    "Fresh Tomato": "product.fresh_tomato",
    "Golden Onion": "product.golden_onion",
    "Fresh Spinach": "product.fresh_spinach",
    "Orange Carrot": "product.orange_carrot",
    "Green Capsicum": "product.green_capsicum",
    "Fresh Garlic": "product.garlic",
    "Green Beans": "product.green_beans",
    "Cauliflower": "product.cauliflower",
    "Broccoli": "product.broccoli",
    "Potato": "product.potato",
    // Fruits
    "Fresh Red Apple": "product.fresh_red_apple",
    "Yellow Bananas": "product.yellow_bananas",
    "Orange": "product.fresh_orange",
    "Ripe Mango": "product.ripe_mango",
    "Fresh Grapes": "product.fresh_grapes",
    "Watermelon": "product.watermelon",
    "Pomegranate": "product.pomegranate",
    "Papaya": "product.papaya",
    "Guava": "product.guava",
    "Pineapple": "product.pineapple",
    // Spices
    "Turmeric Powder": "product.turmeric_powder",
    "Cumin Seeds": "product.cumin_seeds",
    "Chili Powder": "product.red_chili_powder",
    "Coriander": "product.coriander_powder",
    "Garam Masala": "product.garam_masala",
    "Black Pepper": "product.black_pepper",
    "Cardamom": "product.cardamom",
    "Cinnamon": "product.cinnamon",
    "Fenugreek Seeds": "product.fenugreek_seeds",
    "Mustard Seeds": "product.mustard_seeds",
    // Dairy
    "Fresh Milk": "product.fresh_milk",
    "Yogurt": "product.greek_yogurt",
    "Cheese Block": "product.cheddar_cheese",
    "Butter": "product.butter",
    "Paneer": "product.paneer",
    "Cream": "product.cream",
    "Ghee": "product.ghee",
    "Curd": "product.curd",
    "Mozzarella Cheese": "product.mozzarella_cheese",
    "Cottage Cheese": "product.cottage_cheese",
    // Beverages
    "Orange Juice": "product.orange_juice",
    "Premium Tea": "product.premium_tea",
    "Coffee Beans": "product.coffee_beans",
    "Mineral Water": "product.mineral_water",
    "Apple Juice": "product.apple_juice",
    "Green Tea": "product.green_tea",
    "Instant Coffee": "product.instant_coffee",
    "Coconut Water": "product.coconut_water",
    "Lemonade": "product.lemonade",
    "Herbal Tea": "product.herbal_tea",
    // Dry Fruits
    "California Almonds": "product.california_almonds",
    "Cashew Nuts": "product.cashew_nuts",
    "Black Raisins": "product.black_raisins",
    "Premium Dates": "product.dates_pack",
    "Walnuts": "product.walnuts",
    "Pistachios": "product.pistachios",
    "Apricots": "product.apricots",
    "Figs": "product.figs",
    "Hazelnuts": "product.hazelnuts",
    "Prunes": "product.prunes",
    // Chips
    "Potato Chips": "product.potato_chips",
    "Corn Chips": "product.corn_chips",
    "Prawn Chips": "product.prawn_chips",
    "Vegetable Chips": "product.vegetable_chips",
    "Onion Rings": "product.onion_rings",
    "Banana Chips": "product.banana_chips",
    "Tortilla Chips": "product.tortilla_chips",
    "Cheese Chips": "product.cheese_chips",
    "Salt & Vinegar Chips": "product.salt_vinegar_chips",
    "Barbecue Chips": "product.barbecue_chips",
    // Biscuits
    "Digestive Biscuits": "product.digestive_biscuits",
    "Marie Biscuits": "product.marie_biscuits",
    "Chocolate Biscuits": "product.chocolate_biscuits",
    "Wafer Biscuits": "product.wafer_biscuits",
    "Butter Cookies": "product.butter_cookies",
    "Cream Biscuits": "product.cream_biscuits",
    "Oreo Biscuits": "product.oreo_biscuits",
    "Coconut Biscuits": "product.coconut_biscuits",
    "Glucose Biscuits": "product.glucose_biscuits",
    "Honey Biscuits": "product.honey_biscuits",
    // Soaps
    "Natural Soap Bar": "product.natural_soap_bar",
    "Herbal Shampoo": "product.herbal_shampoo",
    "Body Wash": "product.body_wash",
    "Hand Wash": "product.hand_wash",
    "Face Wash": "product.face_wash",
    "Conditioner": "product.conditioner",
    "Liquid Soap": "product.liquid_soap",
    "Shower Gel": "product.shower_gel",
    "Baby Soap": "product.baby_soap",
    "Antiseptic Soap": "product.antiseptic_soap",
    // Namkeen
    "Bhujia": "product.bhujia",
    "Mathri": "product.mathri",
    "Chakli": "product.chakli",
    "Sev": "product.sev",
    "Namkeen Mix": "product.namkeen_mix",
    "Kachori": "product.kachori",
    "Farsan": "product.farsan",
    "Mixture": "product.mixture",
    "Khatta Meetha": "product.khatta_meetha",
    "Masala Peanuts": "product.masala_peanuts",
  }

  const getProductName = (name: string) => {
    const key = productNameMap[name]
    if (!key) return name
    const translated = t(key)
    // If translation returns the key itself (meaning translation doesn't exist), return original name
    return translated === key ? name : translated
  }

  return (
    <PageLayout cartCount={0} onCartClick={() => {}}>
      <div className="max-w-7xl mx-auto px-4 py-12">
        {/* Category Header */}
        <div className="mb-12 text-center animate-fadeInUp">
          <h1 className="text-4xl font-bold text-primary mb-3">{translatedCategoryName}</h1>
          <p className="text-muted-foreground text-lg">{t("category.explore")} {translatedCategoryName.toLowerCase()} {t("category.collection")}</p>
        </div>

        {/* Products Grid */}
        {products.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {products.map((product, index) => (
              <Link
                key={product.id}
                href={`/product/${product.id}`}
                className="group animate-fadeInUp"
                style={{ animationDelay: `${index * 100}ms` }}
              >
                <div className="bg-card border border-border rounded-lg overflow-hidden hover:shadow-2xl hover:border-primary transition-all duration-300 transform hover:scale-105">
                  {/* Product Image */}
                  <div className="relative h-48 bg-background overflow-hidden">
                    <img
                      src={product.image || "/placeholder.svg"}
                      alt={product.name}
                      className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-300"
                    />
                  </div>

                  {/* Product Info */}
                  <div className="p-4">
                    <h3 className="font-semibold text-foreground mb-2 group-hover:text-primary transition-colors line-clamp-2">
                      {getProductName(product.name)}
                    </h3>
                    <p className="text-sm text-muted-foreground mb-3 line-clamp-1">{product.description}</p>

                    {/* Rating */}
                    <div className="flex items-center gap-2 mb-3">
                      <div className="flex gap-1">
                        {[...Array(5)].map((_, i) => (
                          <span
                            key={i}
                            className={`text-sm ${i < Math.floor(product.rating) ? "text-primary" : "text-muted-foreground"}`}
                          >
                            ★
                          </span>
                        ))}
                      </div>
                      <span className="text-xs text-muted-foreground">({product.rating})</span>
                    </div>

                    {/* Price */}
                    <div className="flex items-center justify-between">
                      <span className="text-2xl font-bold text-primary">€{product.price}</span>
                      <button className="px-3 py-1 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors text-sm font-semibold">
                        {t("common.add")}
                      </button>
                    </div>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        ) : (
          <div className="text-center py-12">
            <p className="text-muted-foreground text-lg">{t("shop.no_products")}</p>
          </div>
        )}
      </div>
    </PageLayout>
  )
}
