"use client"

import type React from "react"
import { createContext, useContext, useState } from "react"

type Language = "en" | "pt"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.shop": "Shop",
    "nav.about": "About",
    "nav.deals": "Deals",
    "nav.founders": "Founders",
    "nav.contact": "Contact Us",
    "nav.premium_groceries": "Premium Indian Groceries",

    // Hero
    "hero.premium_quality": "PREMIUM QUALITY",
    "hero.experience": "Experience the",
    "hero.authentic_taste": "Authentic Taste",
    "hero.of_india": "of India",
    "hero.description":
      "Discover premium Indian groceries, fresh produce, aromatic spices, and traditional snacks delivered fresh to your doorstep.",
    "hero.shop_now": "Shop Now",
    "hero.learn_more": "Learn More",

    // Categories
    "cat.vegetables": "Vegetables",
    "cat.fruits": "Fruits",
    "cat.spices": "Spices",
    "cat.dairy": "Dairy",
    "cat.beverages": "Beverages",
    "cat.dryfruits": "Dry Fruits",
    "cat.chips": "Chips",
    "cat.biscuits": "Biscuits",
    "cat.soaps": "Soaps",
    "cat.namkeen": "Namkeen",

    // Footer
    "footer.about": "About Us",
    "footer.quick_links": "Quick Links",
    "footer.contact_info": "Contact Info",
    "footer.follow_us": "Follow Us",
    "footer.all_rights": "All rights reserved",
    "footer.brand_description": "Your trusted source for premium Indian groceries and authentic products.",
    "footer.support": "Support",
    "footer.contact_us": "Contact Us",
    "footer.faq": "FAQ",
    "footer.shipping_info": "Shipping Info",
    "footer.returns": "Returns",
    "footer.track_order": "Track Order",
    "footer.privacy_policy": "Privacy Policy",
    "footer.terms": "Terms & Conditions",

    // Search
    "search.search_products": "Search products...",
    "search.no_results": "No products found",

    // Cart
    "cart.your_cart": "Your Cart",
    "cart.empty": "Your cart is empty",
    "cart.empty_cart": "Your cart is empty",
    "cart.total": "Total",
    "cart.checkout": "Checkout",
    "cart.continue_shopping": "Continue Shopping",
    "cart.start_shopping": "Start Shopping",
    "cart.order_summary": "Order Summary",
    "cart.items": "Items",
    "cart.subtotal": "Subtotal",
    "cart.shipping": "Shipping",
    "cart.free": "Free",

    // Common
    "common.price": "Price",
    "common.rating": "Rating",
    "common.add_to_cart": "Add to Cart",
    "common.view_details": "View Details",
    "common.quantity": "Quantity",
    "common.remove": "Remove",
    "common.add": "Add",
    "common.new": "New",
    "common.off": "OFF",
    "common.get_deal": "Get Deal",
    "common.back": "Back",
    "common.back_to_shop": "Back to Shop",

    // Categories Section
    "categories.title": "Explore Our",
    "categories.categories": "Categories",
    "categories.subtitle": "Handpicked premium products for your kitchen",
    "categories.fresh_vegetables": "Fresh Vegetables",
    "categories.fresh_fruits": "Fresh Fruits",
    "categories.premium_spices": "Premium Spices",
    "categories.dairy": "Dairy",
    "categories.beverages": "Beverages",
    "categories.dry_fruits": "Dry Fruits",
    "categories.chips": "Chips",
    "categories.biscuits": "Biscuits",
    "categories.soaps": "Soaps",
    "categories.namkeen": "Namkeen",
    "categories.view_all": "View All",
    "categories.best_products": "Best products in this category",
    "categories.popular": "Popular",
    "categories.explore": "Explore",

    // Featured Products
    "featured.special_offers": "SPECIAL OFFERS",
    "featured.flash_deals": "Flash",
    "featured.deals": "Deals",
    "featured.subtitle": "Limited time offers on bestsellers",
    "featured.ends_in": "Ends in",
    "featured.up_to": "UP TO",
    "featured.off": "OFF",
    "featured.you_save": "You save",
    "featured.premium_quality": "Premium quality product with amazing discount!",

    // About Section
    "about.title": "ABOUT US",
    "about.heading": "Your Trusted Source for",
    "about.authentic": "Authentic Indian Groceries",
    "about.description": "Since our establishment, King Cash & Carry has been committed to bringing the finest Indian groceries, fresh produce, and authentic spices directly to your doorstep. We believe in quality, freshness, and authenticity.",
    "about.premium_quality": "Premium Quality",
    "about.premium_quality_desc": "Handpicked from trusted suppliers",
    "about.fresh_guarantee": "Fresh Guarantee",
    "about.fresh_guarantee_desc": "Delivered fresh within 24 hours",
    "about.best_prices": "Best Prices",
    "about.best_prices_desc": "Competitive rates without compromising quality",
    "about.explore_more": "Explore More",

    // Newsletter
    "newsletter.title": "Stay Updated with",
    "newsletter.exclusive_offers": "Exclusive Offers",
    "newsletter.subtitle": "Subscribe to our newsletter and get 15% off on your first order!",
    "newsletter.email_placeholder": "Enter your email address",
    "newsletter.subscribe": "Subscribe",
    "newsletter.subscribed": "Subscribed! ✓",
    "newsletter.privacy": "We respect your privacy. Unsubscribe anytime.",

    // Founders Page
    "founders.title": "Meet Our Founders",
    "founders.subtitle": "Visionary leaders driving innovation and excellence in retail and recruitment",
    "founders.mission_title": "Our Mission",
    "founders.mission_text": "Together, we are committed to delivering exceptional value, fostering innovation, and building lasting relationships with our customers and partners across the globe.",

    // Shop Page
    "shop.title": "Our Products",
    "shop.categories": "Categories",
    "shop.all_products": "All Products",
    "shop.sort_by": "Sort By",
    "shop.popular": "Popular",
    "shop.price_low": "Price: Low to High",
    "shop.price_high": "Price: High to Low",
    "shop.highest_rated": "Highest Rated",
    "shop.no_products": "No products found in this category.",

    // Deals Page
    "deals.title": "Amazing Deals & Offers",
    "deals.subtitle": "Limited time offers on your favorite products!",

    // Category Page
    "category.explore": "Explore our premium",
    "category.collection": "collection",

    // Product Names
    "product.fresh_tomato": "Fresh Tomato",
    "product.golden_onion": "Golden Onion",
    "product.fresh_spinach": "Fresh Spinach",
    "product.orange_carrot": "Orange Carrot",
    "product.red_apple": "Red Apple",
    "product.yellow_banana": "Yellow Banana",
    "product.fresh_orange": "Fresh Orange",
    "product.ripe_mango": "Ripe Mango",
    "product.turmeric_powder": "Turmeric Powder",
    "product.cumin_seeds": "Cumin Seeds",
    "product.red_chili_powder": "Red Chili Powder",
    "product.coriander_powder": "Coriander Powder",
    "product.fresh_milk": "Fresh Milk 1L",
    "product.greek_yogurt": "Greek Yogurt",
    "product.cheddar_cheese": "Cheddar Cheese",
    "product.butter": "Butter 200g",
    "product.orange_juice": "Orange Juice",
    "product.premium_tea": "Premium Tea",
    "product.coffee_beans": "Coffee Beans",
    "product.mineral_water": "Mineral Water 1L",
    "product.california_almonds": "California Almonds",
    "product.cashew_nuts": "Cashew Nuts",
    "product.black_raisins": "Black Raisins",
    "product.dates_pack": "Dates Pack",
    "product.potato_chips": "Potato Chips",
    "product.corn_chips": "Corn Chips",
    "product.prawn_chips": "Prawn Chips",
    "product.vegetable_chips": "Vegetable Chips",
    "product.digestive_biscuits": "Digestive Biscuits",
    "product.marie_biscuits": "Marie Biscuits",
    "product.chocolate_biscuits": "Chocolate Biscuits",
    "product.wafer_biscuits": "Wafer Biscuits",
    "product.soap_bar": "Soap Bar 100g",
    "product.shampoo": "Shampoo 200ml",
    "product.body_wash": "Body Wash 250ml",
    "product.handwash": "Handwash 500ml",
    "product.bhujia_snack": "Bhujia Snack",
    "product.mathri_crackers": "Mathri Crackers",
    "product.chakli_pack": "Chakli Pack",
    "product.sev_pack": "Sev Pack",
    "product.organic_tomatoes": "Organic Tomatoes",
    "product.green_capsicum": "Green Capsicum",
    "product.onions": "Onions (1kg)",
    "product.garlic": "Garlic (500g)",
    "product.mangoes": "Mangoes (6pcs)",
    "product.bananas": "Bananas (1kg)",
    "product.apples": "Apples (1kg)",
    "product.oranges": "Oranges (1kg)",
    "product.turmeric_powder_500g": "Turmeric Powder (500g)",
    "product.red_chili_powder_500g": "Red Chili Powder (500g)",
    "product.cumin_seeds_500g": "Cumin Seeds (500g)",
    "product.garam_masala": "Garam Masala (500g)",
    "product.almonds": "Almonds (500g)",
    "product.cashews": "Cashews (500g)",
    "product.walnuts": "Walnuts (500g)",
    "product.raisins": "Raisins (500g)",
    "product.premium_basmati_rice": "Premium Basmati Rice (5kg)",
    "product.masala_chai_tea": "Masala Chai Tea (250g)",
    "product.mixed_namkeen": "Mixed Namkeen (1kg)",
    "product.coconut_oil": "Coconut Oil (500ml)",
    "product.natural_soap_bar": "Natural Soap Bar",
    "product.herbal_shampoo": "Herbal Shampoo",
    "product.hand_wash": "Hand Wash",
    "product.fresh_red_apple": "Fresh Red Apple",
    "product.yellow_bananas": "Yellow Bananas",
    "product.bhujia": "Bhujia",
    "product.mathri": "Mathri",
    "product.chakli": "Chakli",
    "product.sev": "Sev",
    // Additional product translations
    "product.green_beans": "Green Beans",
    "product.cauliflower": "Cauliflower",
    "product.broccoli": "Broccoli",
    "product.potato": "Potato",
    "product.fresh_grapes": "Fresh Grapes",
    "product.watermelon": "Watermelon",
    "product.pomegranate": "Pomegranate",
    "product.papaya": "Papaya",
    "product.guava": "Guava",
    "product.pineapple": "Pineapple",
    "product.black_pepper": "Black Pepper",
    "product.cardamom": "Cardamom",
    "product.cinnamon": "Cinnamon",
    "product.fenugreek_seeds": "Fenugreek Seeds",
    "product.mustard_seeds": "Mustard Seeds",
    "product.paneer": "Paneer",
    "product.cream": "Cream",
    "product.ghee": "Ghee",
    "product.curd": "Curd",
    "product.mozzarella_cheese": "Mozzarella Cheese",
    "product.cottage_cheese": "Cottage Cheese",
    "product.apple_juice": "Apple Juice",
    "product.green_tea": "Green Tea",
    "product.instant_coffee": "Instant Coffee",
    "product.coconut_water": "Coconut Water",
    "product.lemonade": "Lemonade",
    "product.herbal_tea": "Herbal Tea",
    "product.pistachios": "Pistachios",
    "product.apricots": "Apricots",
    "product.figs": "Figs",
    "product.hazelnuts": "Hazelnuts",
    "product.prunes": "Prunes",
    "product.onion_rings": "Onion Rings",
    "product.banana_chips": "Banana Chips",
    "product.tortilla_chips": "Tortilla Chips",
    "product.cheese_chips": "Cheese Chips",
    "product.salt_vinegar_chips": "Salt & Vinegar Chips",
    "product.barbecue_chips": "Barbecue Chips",
    "product.butter_cookies": "Butter Cookies",
    "product.cream_biscuits": "Cream Biscuits",
    "product.oreo_biscuits": "Oreo Biscuits",
    "product.coconut_biscuits": "Coconut Biscuits",
    "product.glucose_biscuits": "Glucose Biscuits",
    "product.honey_biscuits": "Honey Biscuits",
    "product.face_wash": "Face Wash",
    "product.conditioner": "Conditioner",
    "product.liquid_soap": "Liquid Soap",
    "product.shower_gel": "Shower Gel",
    "product.baby_soap": "Baby Soap",
    "product.antiseptic_soap": "Antiseptic Soap",
    "product.namkeen_mix": "Namkeen Mix",
    "product.kachori": "Kachori",
    "product.farsan": "Farsan",
    "product.mixture": "Mixture",
    "product.khatta_meetha": "Khatta Meetha",
    "product.masala_peanuts": "Masala Peanuts",
  },
  pt: {
    // Navigation
    "nav.home": "Início",
    "nav.shop": "Loja",
    "nav.about": "Sobre",
    "nav.deals": "Ofertas",
    "nav.founders": "Fundadores",
    "nav.contact": "Contato",
    "nav.premium_groceries": "Mercearia Premium Indiana",

    // Hero
    "hero.premium_quality": "QUALIDADE PREMIUM",
    "hero.experience": "Experimente o",
    "hero.authentic_taste": "Sabor Autêntico",
    "hero.of_india": "da Índia",
    "hero.description":
      "Descubra alimentos indianos premium, produtos frescos, especiarias aromáticas e lanches tradicionais entregues na sua porta.",
    "hero.shop_now": "Comprar Agora",
    "hero.learn_more": "Saiba Mais",

    // Categories
    "cat.vegetables": "Vegetais",
    "cat.fruits": "Frutas",
    "cat.spices": "Especiarias",
    "cat.dairy": "Laticínios",
    "cat.beverages": "Bebidas",
    "cat.dryfruits": "Frutas Secas",
    "cat.chips": "Batatas Fritas",
    "cat.biscuits": "Biscoitos",
    "cat.soaps": "Sabonetes",
    "cat.namkeen": "Salgadinhos",

    // Footer
    "footer.about": "Sobre Nós",
    "footer.quick_links": "Links Rápidos",
    "footer.contact_info": "Informações de Contato",
    "footer.follow_us": "Siga-nos",
    "footer.all_rights": "Todos os direitos reservados",
    "footer.brand_description": "Sua fonte confiável para alimentos indianos premium e produtos autênticos.",
    "footer.support": "Suporte",
    "footer.contact_us": "Contato",
    "footer.faq": "Perguntas Frequentes",
    "footer.shipping_info": "Informações de Envio",
    "footer.returns": "Devoluções",
    "footer.track_order": "Rastrear Pedido",
    "footer.privacy_policy": "Política de Privacidade",
    "footer.terms": "Termos e Condições",

    // Search
    "search.search_products": "Pesquisar produtos...",
    "search.no_results": "Nenhum produto encontrado",

    // Cart
    "cart.your_cart": "Seu Carrinho",
    "cart.empty": "Seu carrinho está vazio",
    "cart.empty_cart": "Seu carrinho está vazio",
    "cart.total": "Total",
    "cart.checkout": "Finalizar Compra",
    "cart.continue_shopping": "Continuar Comprando",
    "cart.start_shopping": "Começar a Comprar",
    "cart.order_summary": "Resumo do Pedido",
    "cart.items": "Itens",
    "cart.subtotal": "Subtotal",
    "cart.shipping": "Envio",
    "cart.free": "Grátis",

    // Common
    "common.price": "Preço",
    "common.rating": "Avaliação",
    "common.add_to_cart": "Adicionar ao Carrinho",
    "common.view_details": "Ver Detalhes",
    "common.quantity": "Quantidade",
    "common.remove": "Remover",
    "common.add": "Adicionar",
    "common.new": "Novo",
    "common.off": "OFF",
    "common.get_deal": "Obter Oferta",
    "common.back": "Voltar",
    "common.back_to_shop": "Voltar à Loja",

    // Categories Section
    "categories.title": "Explore Nossas",
    "categories.categories": "Categorias",
    "categories.subtitle": "Produtos premium selecionados à mão para sua cozinha",
    "categories.fresh_vegetables": "Vegetais Frescos",
    "categories.fresh_fruits": "Frutas Frescas",
    "categories.premium_spices": "Especiarias Premium",
    "categories.dairy": "Laticínios",
    "categories.beverages": "Bebidas",
    "categories.dry_fruits": "Frutas Secas",
    "categories.chips": "Batatas Fritas",
    "categories.biscuits": "Biscoitos",
    "categories.soaps": "Sabonetes",
    "categories.namkeen": "Salgadinhos",
    "categories.view_all": "Ver Tudo",
    "categories.best_products": "Melhores produtos nesta categoria",
    "categories.popular": "Popular",
    "categories.explore": "Explorar",

    // Featured Products
    "featured.special_offers": "OFERTAS ESPECIAIS",
    "featured.flash_deals": "Ofertas",
    "featured.deals": "Relâmpago",
    "featured.subtitle": "Ofertas por tempo limitado nos mais vendidos",
    "featured.ends_in": "Termina em",
    "featured.up_to": "ATÉ",
    "featured.off": "OFF",
    "featured.you_save": "Você economiza",
    "featured.premium_quality": "Produto de qualidade premium com desconto incrível!",

    // About Section
    "about.title": "SOBRE NÓS",
    "about.heading": "Sua Fonte Confiável para",
    "about.authentic": "Alimentos Indianos Autênticos",
    "about.description": "Desde nossa fundação, a King Cash & Carry tem se comprometido a trazer os melhores alimentos indianos, produtos frescos e especiarias autênticas diretamente para sua porta. Acreditamos em qualidade, frescor e autenticidade.",
    "about.premium_quality": "Qualidade Premium",
    "about.premium_quality_desc": "Selecionados à mão de fornecedores confiáveis",
    "about.fresh_guarantee": "Garantia de Frescor",
    "about.fresh_guarantee_desc": "Entregue fresco em até 24 horas",
    "about.best_prices": "Melhores Preços",
    "about.best_prices_desc": "Preços competitivos sem comprometer a qualidade",
    "about.explore_more": "Explorar Mais",

    // Newsletter
    "newsletter.title": "Mantenha-se Atualizado com",
    "newsletter.exclusive_offers": "Ofertas Exclusivas",
    "newsletter.subtitle": "Inscreva-se em nossa newsletter e ganhe 15% de desconto no seu primeiro pedido!",
    "newsletter.email_placeholder": "Digite seu endereço de e-mail",
    "newsletter.subscribe": "Inscrever-se",
    "newsletter.subscribed": "Inscrito! ✓",
    "newsletter.privacy": "Respeitamos sua privacidade. Cancele a inscrição a qualquer momento.",

    // Founders Page
    "founders.title": "Conheça Nossos Fundadores",
    "founders.subtitle": "Líderes visionários impulsionando inovação e excelência em varejo e recrutamento",
    "founders.mission_title": "Nossa Missão",
    "founders.mission_text": "Juntos, estamos comprometidos em oferecer valor excepcional, promover a inovação e construir relacionamentos duradouros com nossos clientes e parceiros em todo o mundo.",

    // Shop Page
    "shop.title": "Nossos Produtos",
    "shop.categories": "Categorias",
    "shop.all_products": "Todos os Produtos",
    "shop.sort_by": "Ordenar Por",
    "shop.popular": "Popular",
    "shop.price_low": "Preço: Menor para Maior",
    "shop.price_high": "Preço: Maior para Menor",
    "shop.highest_rated": "Mais Bem Avaliados",
    "shop.no_products": "Nenhum produto encontrado nesta categoria.",

    // Deals Page
    "deals.title": "Ofertas e Promoções Incríveis",
    "deals.subtitle": "Ofertas por tempo limitado em seus produtos favoritos!",

    // Category Page
    "category.explore": "Explore nossa coleção premium de",
    "category.collection": "",

    // Product Names
    "product.fresh_tomato": "Tomate Fresco",
    "product.golden_onion": "Cebola Dourada",
    "product.fresh_spinach": "Espinafre Fresco",
    "product.orange_carrot": "Cenoura Laranja",
    "product.red_apple": "Maçã Vermelha",
    "product.yellow_banana": "Banana Amarela",
    "product.fresh_orange": "Laranja Fresca",
    "product.ripe_mango": "Manga Madura",
    "product.turmeric_powder": "Açafrão em Pó",
    "product.cumin_seeds": "Sementes de Cominho",
    "product.red_chili_powder": "Pimenta Vermelha em Pó",
    "product.coriander_powder": "Coentro em Pó",
    "product.fresh_milk": "Leite Fresco 1L",
    "product.greek_yogurt": "Iogurte Grego",
    "product.cheddar_cheese": "Queijo Cheddar",
    "product.butter": "Manteiga 200g",
    "product.orange_juice": "Suco de Laranja",
    "product.premium_tea": "Chá Premium",
    "product.coffee_beans": "Grãos de Café",
    "product.mineral_water": "Água Mineral 1L",
    "product.california_almonds": "Amêndoas da Califórnia",
    "product.cashew_nuts": "Castanha de Caju",
    "product.black_raisins": "Passas Pretas",
    "product.dates_pack": "Pacote de Tâmaras",
    "product.potato_chips": "Batatas Fritas",
    "product.corn_chips": "Chips de Milho",
    "product.prawn_chips": "Chips de Camarão",
    "product.vegetable_chips": "Chips de Vegetais",
    "product.digestive_biscuits": "Biscoitos Digestivos",
    "product.marie_biscuits": "Biscoitos Maria",
    "product.chocolate_biscuits": "Biscoitos de Chocolate",
    "product.wafer_biscuits": "Biscoitos de Wafer",
    "product.soap_bar": "Sabonete 100g",
    "product.shampoo": "Shampoo 200ml",
    "product.body_wash": "Sabonete Líquido 250ml",
    "product.handwash": "Sabonete Líquido 500ml",
    "product.bhujia_snack": "Salgadinho Bhujia",
    "product.mathri_crackers": "Biscoitos Mathri",
    "product.chakli_pack": "Pacote Chakli",
    "product.sev_pack": "Pacote Sev",
    "product.organic_tomatoes": "Tomates Orgânicos",
    "product.green_capsicum": "Pimentão Verde",
    "product.onions": "Cebolas (1kg)",
    "product.garlic": "Alho (500g)",
    "product.mangoes": "Mangas (6 un)",
    "product.bananas": "Bananas (1kg)",
    "product.apples": "Maçãs (1kg)",
    "product.oranges": "Laranjas (1kg)",
    "product.turmeric_powder_500g": "Açafrão em Pó (500g)",
    "product.red_chili_powder_500g": "Pimenta Vermelha em Pó (500g)",
    "product.cumin_seeds_500g": "Sementes de Cominho (500g)",
    "product.garam_masala": "Garam Masala (500g)",
    "product.almonds": "Amêndoas (500g)",
    "product.cashews": "Castanhas de Caju (500g)",
    "product.walnuts": "Nozes (500g)",
    "product.raisins": "Passas (500g)",
    "product.premium_basmati_rice": "Arroz Basmati Premium (5kg)",
    "product.masala_chai_tea": "Chá Masala Chai (250g)",
    "product.mixed_namkeen": "Namkeen Misto (1kg)",
    "product.coconut_oil": "Óleo de Coco (500ml)",
    "product.natural_soap_bar": "Sabonete Natural",
    "product.herbal_shampoo": "Shampoo de Ervas",
    "product.hand_wash": "Sabonete Líquido",
    "product.fresh_red_apple": "Maçã Vermelha Fresca",
    "product.yellow_bananas": "Bananas Amarelas",
    "product.bhujia": "Bhujia",
    "product.mathri": "Mathri",
    "product.chakli": "Chakli",
    "product.sev": "Sev",
    // Additional product translations
    "product.green_beans": "Feijão Verde",
    "product.cauliflower": "Couve-Flor",
    "product.broccoli": "Brócolis",
    "product.potato": "Batata",
    "product.fresh_grapes": "Uvas Frescas",
    "product.watermelon": "Melancia",
    "product.pomegranate": "Romã",
    "product.papaya": "Mamão",
    "product.guava": "Goiaba",
    "product.pineapple": "Abacaxi",
    "product.black_pepper": "Pimenta Preta",
    "product.cardamom": "Cardamomo",
    "product.cinnamon": "Canela",
    "product.fenugreek_seeds": "Sementes de Feno-Grego",
    "product.mustard_seeds": "Sementes de Mostarda",
    "product.paneer": "Paneer",
    "product.cream": "Creme",
    "product.ghee": "Ghee",
    "product.curd": "Coalhada",
    "product.mozzarella_cheese": "Queijo Mussarela",
    "product.cottage_cheese": "Queijo Cottage",
    "product.apple_juice": "Suco de Maçã",
    "product.green_tea": "Chá Verde",
    "product.instant_coffee": "Café Instantâneo",
    "product.coconut_water": "Água de Coco",
    "product.lemonade": "Limonada",
    "product.herbal_tea": "Chá de Ervas",
    "product.pistachios": "Pistácios",
    "product.apricots": "Damasco",
    "product.figs": "Figos",
    "product.hazelnuts": "Avelãs",
    "product.prunes": "Ameixas Secas",
    "product.onion_rings": "Anéis de Cebola",
    "product.banana_chips": "Chips de Banana",
    "product.tortilla_chips": "Chips de Tortilha",
    "product.cheese_chips": "Chips de Queijo",
    "product.salt_vinegar_chips": "Chips Sal e Vinagre",
    "product.barbecue_chips": "Chips de Churrasco",
    "product.butter_cookies": "Biscoitos de Manteiga",
    "product.cream_biscuits": "Biscoitos com Creme",
    "product.oreo_biscuits": "Biscoitos Oreo",
    "product.coconut_biscuits": "Biscoitos de Coco",
    "product.glucose_biscuits": "Biscoitos de Glicose",
    "product.honey_biscuits": "Biscoitos de Mel",
    "product.face_wash": "Sabonete Facial",
    "product.conditioner": "Condicionador",
    "product.liquid_soap": "Sabão Líquido",
    "product.shower_gel": "Gel de Banho",
    "product.baby_soap": "Sabonete para Bebê",
    "product.antiseptic_soap": "Sabonete Antisséptico",
    "product.namkeen_mix": "Mistura Namkeen",
    "product.kachori": "Kachori",
    "product.farsan": "Farsan",
    "product.mixture": "Mistura",
    "product.khatta_meetha": "Khatta Meetha",
    "product.masala_peanuts": "Amendoim Masala",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)["en"]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
