// Shared product data for use across components
export const categoryProducts: Record<string, Array<{ id: string; name: string; price: number; image: string; category: string; rating: number; description: string }>> = {
  flour: [
    { id: "fl1", name: "Wheat Flour", price: 80, image: "/white-basmati-rice-premium.jpg", category: "Flour", rating: 4.7, description: "Premium whole wheat flour" },
    { id: "fl2", name: "All Purpose Flour", price: 75, image: "/white-basmati-rice-premium.jpg", category: "Flour", rating: 4.6, description: "Fine all-purpose white flour" },
    { id: "fl3", name: "Gram Flour", price: 90, image: "/indian-spices-and-vegetables-premium-arrangement.jpg", category: "Flour", rating: 4.8, description: "Pure besan (chickpea flour)" },
    { id: "fl4", name: "Rice Flour", price: 85, image: "/white-basmati-rice-premium.jpg", category: "Flour", rating: 4.5, description: "Fine rice flour for cooking" },
    { id: "fl5", name: "Corn Flour", price: 70, image: "/roasted-corn-chips.jpg", category: "Flour", rating: 4.6, description: "Premium corn flour" },
    { id: "fl6", name: "Ragi Flour", price: 95, image: "/indian-spices-colorful-arrangement.jpg", category: "Flour", rating: 4.7, description: "Nutritious finger millet flour" },
    { id: "fl7", name: "Bajra Flour", price: 88, image: "/indian-spices-turmeric-cumin-cinnamon.jpg", category: "Flour", rating: 4.6, description: "Pearl millet flour" },
    { id: "fl8", name: "Jowar Flour", price: 82, image: "/white-basmati-rice-premium.jpg", category: "Flour", rating: 4.5, description: "Sorghum flour" },
    { id: "fl9", name: "Multigrain Flour", price: 100, image: "/indian-spices-colorful-arrangement.jpg", category: "Flour", rating: 4.8, description: "Healthy multigrain flour mix" },
    { id: "fl10", name: "Maida Flour", price: 72, image: "/white-basmati-rice-premium.jpg", category: "Flour", rating: 4.4, description: "Refined white flour" },
  ],
  rice: [
    { id: "r1", name: "Basmati Rice", price: 120, image: "/white-basmati-rice-premium.jpg", category: "Rice", rating: 4.9, description: "Premium long grain basmati rice" },
    { id: "r2", name: "Sona Masoori Rice", price: 95, image: "/white-basmati-rice-premium.jpg", category: "Rice", rating: 4.7, description: "Popular medium grain rice" },
    { id: "r3", name: "Brown Rice", price: 110, image: "/white-basmati-rice-premium.jpg", category: "Rice", rating: 4.6, description: "Healthy brown rice" },
    { id: "r4", name: "Jasmine Rice", price: 105, image: "/white-basmati-rice-premium.jpg", category: "Rice", rating: 4.8, description: "Fragrant jasmine rice" },
    { id: "r5", name: "Red Rice", price: 115, image: "/white-basmati-rice-premium.jpg", category: "Rice", rating: 4.7, description: "Nutritious red rice" },
    { id: "r6", name: "Black Rice", price: 130, image: "/white-basmati-rice-premium.jpg", category: "Rice", rating: 4.8, description: "Premium black rice" },
    { id: "r7", name: "Steamed Rice", price: 100, image: "/white-basmati-rice-premium.jpg", category: "Rice", rating: 4.5, description: "Parboiled steamed rice" },
    { id: "r8", name: "Short Grain Rice", price: 90, image: "/white-basmati-rice-premium.jpg", category: "Rice", rating: 4.6, description: "Short grain white rice" },
    { id: "r9", name: "Wild Rice", price: 140, image: "/white-basmati-rice-premium.jpg", category: "Rice", rating: 4.9, description: "Premium wild rice" },
    { id: "r10", name: "Sticky Rice", price: 98, image: "/white-basmati-rice-premium.jpg", category: "Rice", rating: 4.7, description: "Glutinous sticky rice" },
  ],
  pulses: [
    { id: "p1", name: "Toor Dal", price: 110, image: "/indian-spices-turmeric-cumin-cinnamon.jpg", category: "Pulses", rating: 4.7, description: "Split pigeon peas" },
    { id: "p2", name: "Moong Dal", price: 105, image: "/indian-spices-and-vegetables-premium-arrangement.jpg", category: "Pulses", rating: 4.6, description: "Split green gram" },
    { id: "p3", name: "Chana Dal", price: 100, image: "/indian-spices-colorful-arrangement.jpg", category: "Pulses", rating: 4.8, description: "Split chickpeas" },
    { id: "p4", name: "Urad Dal", price: 115, image: "/cumin-seeds-spice.jpg", category: "Pulses", rating: 4.7, description: "Split black gram" },
    { id: "p5", name: "Masoor Dal", price: 95, image: "/red-chili-powder.jpg", category: "Pulses", rating: 4.6, description: "Red lentils" },
    { id: "p6", name: "Rajma", price: 120, image: "/indian-spices-and-vegetables-premium-arrangement.jpg", category: "Pulses", rating: 4.8, description: "Kidney beans" },
    { id: "p7", name: "Black Chana", price: 108, image: "/indian-spices-colorful-arrangement.jpg", category: "Pulses", rating: 4.7, description: "Black chickpeas" },
    { id: "p8", name: "White Chana", price: 102, image: "/indian-spices-turmeric-cumin-cinnamon.jpg", category: "Pulses", rating: 4.6, description: "White chickpeas" },
    { id: "p9", name: "Green Moong", price: 98, image: "/cumin-seeds.jpg", category: "Pulses", rating: 4.5, description: "Whole green gram" },
    { id: "p10", name: "Black Urad", price: 112, image: "/indian-spices-colorful-arrangement.jpg", category: "Pulses", rating: 4.7, description: "Whole black gram" },
  ],
  vegetables: [
    { id: "v1", name: "Fresh Tomato", price: 40, image: "/fresh-red-tomato.jpg", category: "Vegetables", rating: 4.5, description: "Freshly picked red tomatoes" },
    { id: "v2", name: "Golden Onion", price: 35, image: "/golden-onion.jpg", category: "Vegetables", rating: 4.3, description: "Sweet and fragrant onions" },
    { id: "v3", name: "Fresh Spinach", price: 30, image: "/fresh-green-spinach.jpg", category: "Vegetables", rating: 4.7, description: "Organic green spinach" },
    { id: "v4", name: "Orange Carrot", price: 45, image: "/orange-carrot.png", category: "Vegetables", rating: 4.6, description: "Crunchy and sweet carrots" },
    { id: "v5", name: "Green Capsicum", price: 60, image: "/fresh-green-capsicum.jpg", category: "Vegetables", rating: 4.4, description: "Fresh green bell peppers" },
    { id: "v6", name: "Fresh Garlic", price: 50, image: "/fresh-garlic-bulbs.jpg", category: "Vegetables", rating: 4.5, description: "Aromatic garlic bulbs" },
    { id: "v7", name: "Green Beans", price: 55, image: "/fresh-organic-vegetables.png", category: "Vegetables", rating: 4.6, description: "Crisp green beans" },
    { id: "v8", name: "Cauliflower", price: 50, image: "/fresh-organic-vegetables.png", category: "Vegetables", rating: 4.5, description: "Fresh white cauliflower" },
    { id: "v9", name: "Broccoli", price: 70, image: "/fresh-organic-vegetables.png", category: "Vegetables", rating: 4.7, description: "Nutritious broccoli florets" },
    { id: "v10", name: "Potato", price: 40, image: "/fresh-organic-vegetables.png", category: "Vegetables", rating: 4.4, description: "Fresh potatoes" },
  ],
  fruits: [
    { id: "f1", name: "Fresh Red Apple", price: 80, image: "/fresh-red-apple.png", category: "Fruits", rating: 4.8, description: "Crispy red apples" },
    { id: "f2", name: "Yellow Bananas", price: 50, image: "/yellow-banana-bunch.png", category: "Fruits", rating: 4.6, description: "Ripe yellow bananas" },
    { id: "f3", name: "Orange", price: 60, image: "/images/orange.png", category: "Fruits", rating: 4.5, description: "Juicy oranges" },
    { id: "f4", name: "Ripe Mango", price: 100, image: "/ripe-mango-fruit.jpg", category: "Fruits", rating: 4.9, description: "Sweet mango perfection" },
    { id: "f5", name: "Fresh Grapes", price: 90, image: "/assorted-fresh-fruits.jpg", category: "Fruits", rating: 4.7, description: "Sweet green grapes" },
    { id: "f6", name: "Watermelon", price: 70, image: "/assorted-fresh-fruits.jpg", category: "Fruits", rating: 4.6, description: "Juicy watermelon" },
    { id: "f7", name: "Pomegranate", price: 120, image: "/assorted-fresh-fruits.jpg", category: "Fruits", rating: 4.8, description: "Fresh pomegranate" },
    { id: "f8", name: "Papaya", price: 55, image: "/assorted-fresh-fruits.jpg", category: "Fruits", rating: 4.5, description: "Ripe papaya" },
    { id: "f9", name: "Guava", price: 45, image: "/assorted-fresh-fruits.jpg", category: "Fruits", rating: 4.6, description: "Fresh guava" },
    { id: "f10", name: "Pineapple", price: 85, image: "/assorted-fresh-fruits.jpg", category: "Fruits", rating: 4.7, description: "Sweet pineapple" },
  ],
  spices: [
    { id: "s1", name: "Turmeric Powder", price: 120, image: "/turmeric-powder.png", category: "Spices", rating: 4.7, description: "Pure turmeric powder" },
    { id: "s2", name: "Cumin Seeds", price: 150, image: "/cumin-seeds-spice.jpg", category: "Spices", rating: 4.6, description: "Aromatic cumin seeds" },
    { id: "s3", name: "Chili Powder", price: 100, image: "/red-chili-powder.jpg", category: "Spices", rating: 4.8, description: "Red chili powder" },
    { id: "s4", name: "Coriander", price: 130, image: "/coriander-powder.jpg", category: "Spices", rating: 4.5, description: "Fresh coriander powder" },
    { id: "s5", name: "Garam Masala", price: 180, image: "/indian-spices-turmeric-cumin-cinnamon.jpg", category: "Spices", rating: 4.9, description: "Aromatic garam masala" },
    { id: "s6", name: "Black Pepper", price: 140, image: "/indian-spices-colorful-arrangement.jpg", category: "Spices", rating: 4.6, description: "Whole black pepper" },
    { id: "s7", name: "Cardamom", price: 200, image: "/indian-spices-colorful-arrangement.jpg", category: "Spices", rating: 4.8, description: "Green cardamom pods" },
    { id: "s8", name: "Cinnamon", price: 160, image: "/indian-spices-turmeric-cumin-cinnamon.jpg", category: "Spices", rating: 4.7, description: "Cinnamon sticks" },
    { id: "s9", name: "Fenugreek Seeds", price: 110, image: "/indian-spices-colorful-arrangement.jpg", category: "Spices", rating: 4.5, description: "Fenugreek seeds" },
    { id: "s10", name: "Mustard Seeds", price: 90, image: "/indian-spices-colorful-arrangement.jpg", category: "Spices", rating: 4.6, description: "Yellow mustard seeds" },
  ],
  dairy: [
    { id: "d1", name: "Fresh Milk", price: 65, image: "/fresh-milk-carton.jpg", category: "Dairy", rating: 4.7, description: "Pure fresh milk" },
    { id: "d2", name: "Yogurt", price: 50, image: "/yogurt-container.jpg", category: "Dairy", rating: 4.6, description: "Creamy yogurt" },
    { id: "d3", name: "Cheese Block", price: 250, image: "/cheese-block.png", category: "Dairy", rating: 4.8, description: "Premium cheese" },
    { id: "d4", name: "Butter", price: 180, image: "/butter-pack.jpg", category: "Dairy", rating: 4.5, description: "Creamy butter" },
    { id: "d5", name: "Paneer", price: 200, image: "/fresh-milk-carton.jpg", category: "Dairy", rating: 4.7, description: "Fresh paneer" },
    { id: "d6", name: "Cream", price: 120, image: "/fresh-milk-carton.jpg", category: "Dairy", rating: 4.6, description: "Fresh cream" },
    { id: "d7", name: "Ghee", price: 350, image: "/butter-pack.jpg", category: "Dairy", rating: 4.9, description: "Pure desi ghee" },
    { id: "d8", name: "Curd", price: 45, image: "/yogurt-container.jpg", category: "Dairy", rating: 4.6, description: "Fresh curd" },
    { id: "d9", name: "Mozzarella Cheese", price: 280, image: "/cheese-block.png", category: "Dairy", rating: 4.8, description: "Mozzarella cheese" },
    { id: "d10", name: "Cottage Cheese", price: 150, image: "/cheese-block.png", category: "Dairy", rating: 4.7, description: "Fresh cottage cheese" },
  ],
  beverages: [
    { id: "b1", name: "Orange Juice", price: 80, image: "/orange-juice-bottle.jpg", category: "Beverages", rating: 4.6, description: "Fresh orange juice" },
    { id: "b2", name: "Premium Tea", price: 200, image: "/premium-tea-leaves.jpg", category: "Beverages", rating: 4.8, description: "Premium tea leaves" },
    { id: "b3", name: "Coffee Beans", price: 250, image: "/coffee-beans-roasted.jpg", category: "Beverages", rating: 4.9, description: "Roasted coffee beans" },
    { id: "b4", name: "Mineral Water", price: 30, image: "/mineral-water-bottle.jpg", category: "Beverages", rating: 4.4, description: "Pure mineral water" },
    { id: "b5", name: "Apple Juice", price: 85, image: "/orange-juice-bottle.jpg", category: "Beverages", rating: 4.5, description: "Fresh apple juice" },
    { id: "b6", name: "Green Tea", price: 180, image: "/premium-tea-leaves.jpg", category: "Beverages", rating: 4.7, description: "Organic green tea" },
    { id: "b7", name: "Instant Coffee", price: 150, image: "/coffee-beans-roasted.jpg", category: "Beverages", rating: 4.6, description: "Instant coffee powder" },
    { id: "b8", name: "Coconut Water", price: 40, image: "/mineral-water-bottle.jpg", category: "Beverages", rating: 4.8, description: "Fresh coconut water" },
    { id: "b9", name: "Lemonade", price: 45, image: "/orange-juice-bottle.jpg", category: "Beverages", rating: 4.5, description: "Fresh lemonade" },
    { id: "b10", name: "Herbal Tea", price: 220, image: "/premium-tea-leaves.jpg", category: "Beverages", rating: 4.7, description: "Herbal tea blend" },
  ],
  "dry-fruits": [
    { id: "df1", name: "California Almonds", price: 500, image: "/california-almonds-nuts.jpg", category: "Dry Fruits", rating: 4.9, description: "Premium almonds" },
    { id: "df2", name: "Cashew Nuts", price: 450, image: "/cashew-nuts-roasted.jpg", category: "Dry Fruits", rating: 4.8, description: "Roasted cashews" },
    { id: "df3", name: "Black Raisins", price: 200, image: "/black-raisins-dried.jpg", category: "Dry Fruits", rating: 4.6, description: "Dried raisins" },
    { id: "df4", name: "Premium Dates", price: 300, image: "/premium-dates-fruit.jpg", category: "Dry Fruits", rating: 4.7, description: "Premium dates" },
    { id: "df5", name: "Walnuts", price: 550, image: "/dry-fruits-almonds-cashews-raisins.jpg", category: "Dry Fruits", rating: 4.8, description: "Premium walnuts" },
    { id: "df6", name: "Pistachios", price: 600, image: "/dry-fruits-almonds-cashews-raisins.jpg", category: "Dry Fruits", rating: 4.9, description: "Green pistachios" },
    { id: "df7", name: "Apricots", price: 350, image: "/black-raisins-dried.jpg", category: "Dry Fruits", rating: 4.7, description: "Dried apricots" },
    { id: "df8", name: "Figs", price: 400, image: "/premium-dates-fruit.jpg", category: "Dry Fruits", rating: 4.6, description: "Dried figs" },
    { id: "df9", name: "Hazelnuts", price: 520, image: "/california-almonds-nuts.jpg", category: "Dry Fruits", rating: 4.8, description: "Roasted hazelnuts" },
    { id: "df10", name: "Prunes", price: 280, image: "/black-raisins-dried.jpg", category: "Dry Fruits", rating: 4.5, description: "Dried prunes" },
  ],
  chips: [
    { id: "c1", name: "Potato Chips", price: 40, image: "/crispy-potato-chips.jpg", category: "Chips", rating: 4.5, description: "Crispy potato chips" },
    { id: "c2", name: "Corn Chips", price: 45, image: "/roasted-corn-chips.jpg", category: "Chips", rating: 4.6, description: "Roasted corn chips" },
    { id: "c3", name: "Prawn Chips", price: 80, image: "/spicy-prawn-chips.jpg", category: "Chips", rating: 4.7, description: "Spicy prawn chips" },
    { id: "c4", name: "Vegetable Chips", price: 50, image: "/healthy-vegetable-chips.jpg", category: "Chips", rating: 4.8, description: "Healthy vegetable chips" },
    { id: "c5", name: "Onion Rings", price: 55, image: "/crispy-potato-chips.jpg", category: "Chips", rating: 4.6, description: "Crispy onion rings" },
    { id: "c6", name: "Banana Chips", price: 60, image: "/roasted-corn-chips.jpg", category: "Chips", rating: 4.7, description: "Sweet banana chips" },
    { id: "c7", name: "Tortilla Chips", price: 48, image: "/roasted-corn-chips.jpg", category: "Chips", rating: 4.5, description: "Mexican tortilla chips" },
    { id: "c8", name: "Cheese Chips", price: 65, image: "/crispy-potato-chips.jpg", category: "Chips", rating: 4.8, description: "Cheesy chips" },
    { id: "c9", name: "Salt & Vinegar Chips", price: 42, image: "/crispy-potato-chips.jpg", category: "Chips", rating: 4.6, description: "Tangy salt & vinegar" },
    { id: "c10", name: "Barbecue Chips", price: 45, image: "/spicy-prawn-chips.jpg", category: "Chips", rating: 4.7, description: "Smoky barbecue flavor" },
  ],
  biscuits: [
    { id: "bi1", name: "Digestive Biscuits", price: 60, image: "/whole-wheat-digestive-biscuits.jpg", category: "Biscuits", rating: 4.6, description: "Whole wheat digestive" },
    { id: "bi2", name: "Marie Biscuits", price: 50, image: "/light-crispy-marie-biscuits.jpg", category: "Biscuits", rating: 4.5, description: "Light and crispy" },
    { id: "bi3", name: "Chocolate Biscuits", price: 70, image: "/chocolate-biscuits.jpg", category: "Biscuits", rating: 4.7, description: "Chocolate biscuits" },
    { id: "bi4", name: "Wafer Biscuits", price: 65, image: "/wafer-biscuits.jpg", category: "Biscuits", rating: 4.6, description: "Thin wafer biscuits" },
    { id: "bi5", name: "Butter Cookies", price: 75, image: "/chocolate-biscuits.jpg", category: "Biscuits", rating: 4.8, description: "Buttery cookies" },
    { id: "bi6", name: "Cream Biscuits", price: 68, image: "/whole-wheat-digestive-biscuits.jpg", category: "Biscuits", rating: 4.7, description: "Cream filled biscuits" },
    { id: "bi7", name: "Oreo Biscuits", price: 80, image: "/chocolate-biscuits.jpg", category: "Biscuits", rating: 4.9, description: "Chocolate cream cookies" },
    { id: "bi8", name: "Coconut Biscuits", price: 62, image: "/light-crispy-marie-biscuits.jpg", category: "Biscuits", rating: 4.6, description: "Coconut flavored" },
    { id: "bi9", name: "Glucose Biscuits", price: 45, image: "/whole-wheat-digestive-biscuits.jpg", category: "Biscuits", rating: 4.5, description: "Energy biscuits" },
    { id: "bi10", name: "Honey Biscuits", price: 58, image: "/wafer-biscuits.jpg", category: "Biscuits", rating: 4.7, description: "Honey sweetened" },
  ],
  soaps: [
    { id: "so1", name: "Natural Soap Bar", price: 80, image: "/natural-soap-bar.jpg", category: "Soaps", rating: 4.6, description: "Natural soap bar" },
    { id: "so2", name: "Herbal Shampoo", price: 150, image: "/herbal-shampoo.jpg", category: "Soaps", rating: 4.7, description: "Herbal shampoo" },
    { id: "so3", name: "Body Wash", price: 120, image: "/body-wash.jpg", category: "Soaps", rating: 4.5, description: "Gentle body wash" },
    { id: "so4", name: "Hand Wash", price: 100, image: "/hand-wash.jpg", category: "Soaps", rating: 4.8, description: "Antibacterial hand wash" },
    { id: "so5", name: "Face Wash", price: 130, image: "/natural-soap-bar.jpg", category: "Soaps", rating: 4.7, description: "Gentle face wash" },
    { id: "so6", name: "Conditioner", price: 140, image: "/herbal-shampoo.jpg", category: "Soaps", rating: 4.6, description: "Hair conditioner" },
    { id: "so7", name: "Liquid Soap", price: 90, image: "/hand-wash.jpg", category: "Soaps", rating: 4.5, description: "Liquid hand soap" },
    { id: "so8", name: "Shower Gel", price: 110, image: "/body-wash.jpg", category: "Soaps", rating: 4.6, description: "Refreshing shower gel" },
    { id: "so9", name: "Baby Soap", price: 70, image: "/natural-soap-bar.jpg", category: "Soaps", rating: 4.8, description: "Gentle baby soap" },
    { id: "so10", name: "Antiseptic Soap", price: 85, image: "/natural-soap-bar.jpg", category: "Soaps", rating: 4.7, description: "Antiseptic soap bar" },
  ],
  namkeen: [
    { id: "n1", name: "Bhujia", price: 60, image: "/bhujia-snack.jpg", category: "Namkeen", rating: 4.7, description: "Spicy bhujia" },
    { id: "n2", name: "Mathri", price: 70, image: "/mathri-snack.jpg", category: "Namkeen", rating: 4.6, description: "Crispy mathri" },
    { id: "n3", name: "Chakli", price: 80, image: "/chakli-snack.jpg", category: "Namkeen", rating: 4.8, description: "Twisted chakli" },
    { id: "n4", name: "Sev", price: 65, image: "/sev-snack.jpg", category: "Namkeen", rating: 4.5, description: "Delicious sev" },
    { id: "n5", name: "Namkeen Mix", price: 75, image: "/indian-namkeen-snacks-mix.jpg", category: "Namkeen", rating: 4.8, description: "Mixed namkeen" },
    { id: "n6", name: "Kachori", price: 85, image: "/mathri-snack.jpg", category: "Namkeen", rating: 4.7, description: "Spicy kachori" },
    { id: "n7", name: "Farsan", price: 68, image: "/indian-namkeen-snacks-mix.jpg", category: "Namkeen", rating: 4.6, description: "Gujarati farsan" },
    { id: "n8", name: "Mixture", price: 72, image: "/indian-namkeen-snacks-mix.jpg", category: "Namkeen", rating: 4.7, description: "Crispy mixture" },
    { id: "n9", name: "Khatta Meetha", price: 78, image: "/bhujia-snack.jpg", category: "Namkeen", rating: 4.8, description: "Sweet and sour" },
    { id: "n10", name: "Masala Peanuts", price: 55, image: "/indian-namkeen-snacks-mix.jpg", category: "Namkeen", rating: 4.6, description: "Spicy peanuts" },
  ],
}

