"use client"

import { useState } from "react"
import { useParams } from "next/navigation"
import Link from "next/link"
import { ShoppingCart, ArrowLeft, Star } from "lucide-react"
import { useLanguage } from "@/lib/language-context"
import PageLayout from "@/components/page-layout"

// All products from category pages - flattened into single array with all 10 products per category
const allProducts = [
  // Vegetables (10 products)
  {
    id: "v1",
    name: "Fresh Tomato",
    category: "Vegetables",
    price: 40,
    rating: 4.5,
    reviews: 234,
    image: "/fresh-red-tomato.jpg",
    description: "Freshly picked red tomatoes",
    details: "Fresh tomatoes are rich in vitamin C and lycopene. Our tomatoes are hand-picked at peak ripeness to ensure maximum freshness and flavor.",
  },
  {
    id: "v2",
    name: "Golden Onion",
    category: "Vegetables",
    price: 35,
    rating: 4.3,
    reviews: 156,
    image: "/golden-onion.jpg",
    description: "Sweet and fragrant onions",
    details: "Golden onions are a staple ingredient in Indian cooking. Rich in antioxidants and anti-inflammatory properties.",
  },
  {
    id: "v3",
    name: "Fresh Spinach",
    category: "Vegetables",
    price: 30,
    rating: 4.7,
    reviews: 189,
    image: "/fresh-green-spinach.jpg",
    description: "Organic green spinach",
    details: "Rich in iron and essential minerals, our organic spinach is pesticide-free and sourced from trusted farms.",
  },
  {
    id: "v4",
    name: "Orange Carrot",
    category: "Vegetables",
    price: 45,
    rating: 4.6,
    reviews: 167,
    image: "/orange-carrot.png",
    description: "Crunchy and sweet carrots",
    details: "Fresh carrots packed with beta-carotene and vitamin A for better health.",
  },
  {
    id: "v5",
    name: "Green Capsicum",
    category: "Vegetables",
    price: 60,
    rating: 4.4,
    reviews: 145,
    image: "/fresh-green-capsicum.jpg",
    description: "Fresh green bell peppers",
    details: "Crisp and fresh green capsicum perfect for cooking and salads. Rich in vitamin C.",
  },
  {
    id: "v6",
    name: "Fresh Garlic",
    category: "Vegetables",
    price: 50,
    rating: 4.5,
    reviews: 178,
    image: "/fresh-garlic-bulbs.jpg",
    description: "Aromatic garlic bulbs",
    details: "Fresh garlic bulbs with strong aroma and flavor. Essential for Indian cuisine.",
  },
  {
    id: "v7",
    name: "Green Beans",
    category: "Vegetables",
    price: 55,
    rating: 4.6,
    reviews: 134,
    image: "/fresh-organic-vegetables.png",
    description: "Crisp green beans",
    details: "Fresh green beans rich in fiber and vitamins. Perfect for stir-fries and curries.",
  },
  {
    id: "v8",
    name: "Cauliflower",
    category: "Vegetables",
    price: 50,
    rating: 4.5,
    reviews: 198,
    image: "/fresh-organic-vegetables.png",
    description: "Fresh white cauliflower",
    details: "Fresh cauliflower florets perfect for making delicious curries and snacks.",
  },
  {
    id: "v9",
    name: "Broccoli",
    category: "Vegetables",
    price: 70,
    rating: 4.7,
    reviews: 167,
    image: "/fresh-organic-vegetables.png",
    description: "Nutritious broccoli florets",
    details: "Fresh broccoli packed with vitamins and antioxidants. Great for healthy meals.",
  },
  {
    id: "v10",
    name: "Potato",
    category: "Vegetables",
    price: 40,
    rating: 4.4,
    reviews: 289,
    image: "/fresh-organic-vegetables.png",
    description: "Fresh potatoes",
    details: "Fresh potatoes perfect for all your cooking needs. Versatile and nutritious.",
  },

  // Fruits (10 products)
  {
    id: "f1",
    name: "Fresh Red Apple",
    category: "Fruits",
    price: 80,
    rating: 4.8,
    reviews: 312,
    image: "/fresh-red-apple.png",
    description: "Crispy red apples",
    details: "Premium Kashmir apples known for their sweet taste and crispy texture. Rich in fiber and antioxidants.",
  },
  {
    id: "f2",
    name: "Yellow Bananas",
    category: "Fruits",
    price: 50,
    rating: 4.6,
    reviews: 278,
    image: "/yellow-banana-bunch.png",
    description: "Ripe yellow bananas",
    details: "Yellow bananas are rich in potassium and B vitamins. Perfect for breakfast or snacking.",
  },
  {
    id: "f3",
    name: "Orange",
    category: "Fruits",
    price: 60,
    rating: 4.5,
    reviews: 245,
    image: "/images/orange.png",
    description: "Juicy oranges",
    details: "Fresh oranges loaded with vitamin C and natural antioxidants.",
  },
  {
    id: "f4",
    name: "Ripe Mango",
    category: "Fruits",
    price: 100,
    rating: 4.9,
    reviews: 356,
    image: "/ripe-mango-fruit.jpg",
    description: "Sweet mango perfection",
    details: "King of fruits! Alphonso mangoes are known for their sweet taste and aromatic flavor.",
  },
  {
    id: "f5",
    name: "Fresh Grapes",
    category: "Fruits",
    price: 90,
    rating: 4.7,
    reviews: 189,
    image: "/assorted-fresh-fruits.jpg",
    description: "Sweet green grapes",
    details: "Fresh sweet grapes perfect for snacking. Rich in antioxidants and natural sugars.",
  },
  {
    id: "f6",
    name: "Watermelon",
    category: "Fruits",
    price: 70,
    rating: 4.6,
    reviews: 234,
    image: "/assorted-fresh-fruits.jpg",
    description: "Juicy watermelon",
    details: "Fresh and juicy watermelon perfect for hot days. High in water content and refreshing.",
  },
  {
    id: "f7",
    name: "Pomegranate",
    category: "Fruits",
    price: 120,
    rating: 4.8,
    reviews: 167,
    image: "/assorted-fresh-fruits.jpg",
    description: "Fresh pomegranate",
    details: "Fresh pomegranate seeds rich in antioxidants. Great for health and taste.",
  },
  {
    id: "f8",
    name: "Papaya",
    category: "Fruits",
    price: 55,
    rating: 4.5,
    reviews: 145,
    image: "/assorted-fresh-fruits.jpg",
    description: "Ripe papaya",
    details: "Ripe papaya rich in vitamin C and digestive enzymes. Perfect for breakfast.",
  },
  {
    id: "f9",
    name: "Guava",
    category: "Fruits",
    price: 45,
    rating: 4.6,
    reviews: 178,
    image: "/assorted-fresh-fruits.jpg",
    description: "Fresh guava",
    details: "Fresh guava with sweet and tangy flavor. Rich in vitamin C and fiber.",
  },
  {
    id: "f10",
    name: "Pineapple",
    category: "Fruits",
    price: 85,
    rating: 4.7,
    reviews: 198,
    image: "/assorted-fresh-fruits.jpg",
    description: "Sweet pineapple",
    details: "Fresh sweet pineapple perfect for desserts and juices. Rich in vitamin C.",
  },

  // Spices (10 products)
  {
    id: "s1",
    name: "Turmeric Powder",
    category: "Spices",
    price: 120,
    rating: 4.7,
    reviews: 445,
    image: "/turmeric-powder.png",
    description: "Pure turmeric powder",
    details: "100% pure turmeric powder with curcumin content. Used in Indian cooking and traditional medicine.",
  },
  {
    id: "s2",
    name: "Cumin Seeds",
    category: "Spices",
    price: 150,
    rating: 4.6,
    reviews: 289,
    image: "/cumin-seeds-spice.jpg",
    description: "Aromatic cumin seeds",
    details: "Premium aromatic cumin seeds from Gujarat. Essential for Indian cuisine.",
  },
  {
    id: "s3",
    name: "Chili Powder",
    category: "Spices",
    price: 100,
    rating: 4.8,
    reviews: 234,
    image: "/red-chili-powder.jpg",
    description: "Red chili powder",
    details: "Pure red chili powder for adding that perfect heat to your dishes.",
  },
  {
    id: "s4",
    name: "Coriander",
    category: "Spices",
    price: 130,
    rating: 4.5,
    reviews: 267,
    image: "/coriander-powder.jpg",
    description: "Fresh coriander powder",
    details: "Fresh ground coriander powder with rich aroma and flavor.",
  },
  {
    id: "s5",
    name: "Garam Masala",
    category: "Spices",
    price: 180,
    rating: 4.9,
    reviews: 356,
    image: "/indian-spices-turmeric-cumin-cinnamon.jpg",
    description: "Aromatic garam masala",
    details: "Premium garam masala blend with perfect mix of aromatic spices for authentic Indian flavor.",
  },
  {
    id: "s6",
    name: "Black Pepper",
    category: "Spices",
    price: 140,
    rating: 4.6,
    reviews: 198,
    image: "/indian-spices-colorful-arrangement.jpg",
    description: "Whole black pepper",
    details: "Premium whole black pepper corns with strong aroma and flavor.",
  },
  {
    id: "s7",
    name: "Cardamom",
    category: "Spices",
    price: 200,
    rating: 4.8,
    reviews: 234,
    image: "/indian-spices-colorful-arrangement.jpg",
    description: "Green cardamom pods",
    details: "Premium green cardamom pods with aromatic flavor. Essential for Indian sweets and tea.",
  },
  {
    id: "s8",
    name: "Cinnamon",
    category: "Spices",
    price: 160,
    rating: 4.7,
    reviews: 189,
    image: "/indian-spices-turmeric-cumin-cinnamon.jpg",
    description: "Cinnamon sticks",
    details: "Premium cinnamon sticks with sweet and warm flavor. Perfect for desserts and curries.",
  },
  {
    id: "s9",
    name: "Fenugreek Seeds",
    category: "Spices",
    price: 110,
    rating: 4.5,
    reviews: 156,
    image: "/indian-spices-colorful-arrangement.jpg",
    description: "Fenugreek seeds",
    details: "Fenugreek seeds with unique bitter flavor. Great for tempering and health benefits.",
  },
  {
    id: "s10",
    name: "Mustard Seeds",
    category: "Spices",
    price: 90,
    rating: 4.6,
    reviews: 178,
    image: "/indian-spices-colorful-arrangement.jpg",
    description: "Yellow mustard seeds",
    details: "Yellow mustard seeds perfect for tempering and pickling. Essential for Indian cooking.",
  },

  // Dairy (10 products)
  {
    id: "d1",
    name: "Fresh Milk",
    category: "Dairy",
    price: 65,
    rating: 4.7,
    reviews: 423,
    image: "/fresh-milk-carton.jpg",
    description: "Pure fresh milk",
    details: "Pure pasteurized milk from healthy cows. Great source of calcium and protein.",
  },
  {
    id: "d2",
    name: "Yogurt",
    category: "Dairy",
    price: 50,
    rating: 4.6,
    reviews: 298,
    image: "/yogurt-container.jpg",
    description: "Creamy yogurt",
    details: "Thick and creamy yogurt rich in probiotics for digestive health.",
  },
  {
    id: "d3",
    name: "Cheese Block",
    category: "Dairy",
    price: 250,
    rating: 4.8,
    reviews: 256,
    image: "/cheese-block.png",
    description: "Premium cheese",
    details: "Sharp and flavorful cheese perfect for cooking and snacking.",
  },
  {
    id: "d4",
    name: "Butter",
    category: "Dairy",
    price: 180,
    rating: 4.5,
    reviews: 389,
    image: "/butter-pack.jpg",
    description: "Creamy butter",
    details: "Pure, creamy butter made from fresh cream. Perfect for cooking and baking.",
  },
  {
    id: "d5",
    name: "Paneer",
    category: "Dairy",
    price: 200,
    rating: 4.7,
    reviews: 312,
    image: "/fresh-milk-carton.jpg",
    description: "Fresh paneer",
    details: "Fresh homemade paneer perfect for curries and snacks. Rich in protein.",
  },
  {
    id: "d6",
    name: "Cream",
    category: "Dairy",
    price: 120,
    rating: 4.6,
    reviews: 198,
    image: "/fresh-milk-carton.jpg",
    description: "Fresh cream",
    details: "Fresh cream perfect for desserts and cooking. Rich and creamy texture.",
  },
  {
    id: "d7",
    name: "Ghee",
    category: "Dairy",
    price: 350,
    rating: 4.9,
    reviews: 445,
    image: "/butter-pack.jpg",
    description: "Pure desi ghee",
    details: "Pure desi ghee made from fresh butter. Essential for Indian cooking and health benefits.",
  },
  {
    id: "d8",
    name: "Curd",
    category: "Dairy",
    price: 45,
    rating: 4.6,
    reviews: 267,
    image: "/yogurt-container.jpg",
    description: "Fresh curd",
    details: "Fresh homemade curd with probiotics. Perfect for meals and health.",
  },
  {
    id: "d9",
    name: "Mozzarella Cheese",
    category: "Dairy",
    price: 280,
    rating: 4.8,
    reviews: 234,
    image: "/cheese-block.png",
    description: "Mozzarella cheese",
    details: "Premium mozzarella cheese perfect for pizzas and Italian dishes.",
  },
  {
    id: "d10",
    name: "Cottage Cheese",
    category: "Dairy",
    price: 150,
    rating: 4.7,
    reviews: 189,
    image: "/cheese-block.png",
    description: "Fresh cottage cheese",
    details: "Fresh cottage cheese rich in protein. Perfect for healthy meals.",
  },

  // Beverages (10 products)
  {
    id: "b1",
    name: "Orange Juice",
    category: "Beverages",
    price: 80,
    rating: 4.6,
    reviews: 234,
    image: "/orange-juice-bottle.jpg",
    description: "Fresh orange juice",
    details: "100% fresh squeezed orange juice with no added preservatives or sugar.",
  },
  {
    id: "b2",
    name: "Premium Tea",
    category: "Beverages",
    price: 200,
    rating: 4.8,
    reviews: 367,
    image: "/premium-tea-leaves.jpg",
    description: "Premium tea leaves",
    details: "Premium Darjeeling tea with rich aroma and delicate flavor. First flush collection.",
  },
  {
    id: "b3",
    name: "Coffee Beans",
    category: "Beverages",
    price: 250,
    rating: 4.9,
    reviews: 245,
    image: "/coffee-beans-roasted.jpg",
    description: "Roasted coffee beans",
    details: "Premium Arabica coffee beans freshly roasted to perfection.",
  },
  {
    id: "b4",
    name: "Mineral Water",
    category: "Beverages",
    price: 30,
    rating: 4.4,
    reviews: 156,
    image: "/mineral-water-bottle.jpg",
    description: "Pure mineral water",
    details: "Purified mineral water rich in essential minerals for hydration.",
  },
  {
    id: "b5",
    name: "Apple Juice",
    category: "Beverages",
    price: 85,
    rating: 4.5,
    reviews: 178,
    image: "/orange-juice-bottle.jpg",
    description: "Fresh apple juice",
    details: "Fresh apple juice with natural sweetness. Rich in vitamins.",
  },
  {
    id: "b6",
    name: "Green Tea",
    category: "Beverages",
    price: 180,
    rating: 4.7,
    reviews: 289,
    image: "/premium-tea-leaves.jpg",
    description: "Organic green tea",
    details: "Organic green tea with antioxidants. Great for health and wellness.",
  },
  {
    id: "b7",
    name: "Instant Coffee",
    category: "Beverages",
    price: 150,
    rating: 4.6,
    reviews: 234,
    image: "/coffee-beans-roasted.jpg",
    description: "Instant coffee powder",
    details: "Premium instant coffee powder for quick and delicious coffee.",
  },
  {
    id: "b8",
    name: "Coconut Water",
    category: "Beverages",
    price: 40,
    rating: 4.8,
    reviews: 198,
    image: "/mineral-water-bottle.jpg",
    description: "Fresh coconut water",
    details: "Fresh coconut water rich in electrolytes. Perfect for hydration.",
  },
  {
    id: "b9",
    name: "Lemonade",
    category: "Beverages",
    price: 45,
    rating: 4.5,
    reviews: 167,
    image: "/orange-juice-bottle.jpg",
    description: "Fresh lemonade",
    details: "Fresh lemonade with natural lemon flavor. Refreshing and healthy.",
  },
  {
    id: "b10",
    name: "Herbal Tea",
    category: "Beverages",
    price: 220,
    rating: 4.7,
    reviews: 256,
    image: "/premium-tea-leaves.jpg",
    description: "Herbal tea blend",
    details: "Premium herbal tea blend with natural herbs for health benefits.",
  },

  // Dry Fruits (10 products)
  {
    id: "df1",
    name: "California Almonds",
    category: "Dry Fruits",
    price: 500,
    rating: 4.9,
    reviews: 512,
    image: "/california-almonds-nuts.jpg",
    description: "Premium almonds",
    details: "Premium California almonds packed with protein, fiber, and healthy fats. Perfect for daily snacking.",
  },
  {
    id: "df2",
    name: "Cashew Nuts",
    category: "Dry Fruits",
    price: 450,
    rating: 4.8,
    reviews: 423,
    image: "/cashew-nuts-roasted.jpg",
    description: "Roasted cashews",
    details: "Delicious roasted cashew nuts rich in minerals and antioxidants.",
  },
  {
    id: "df3",
    name: "Black Raisins",
    category: "Dry Fruits",
    price: 200,
    rating: 4.6,
    reviews: 289,
    image: "/black-raisins-dried.jpg",
    description: "Dried raisins",
    details: "Sweet black raisins perfect for cooking, baking, or eating straight from the package.",
  },
  {
    id: "df4",
    name: "Premium Dates",
    category: "Dry Fruits",
    price: 300,
    rating: 4.7,
    reviews: 334,
    image: "/premium-dates-fruit.jpg",
    description: "Premium dates",
    details: "Premium date fruits rich in natural sugars and essential nutrients.",
  },
  {
    id: "df5",
    name: "Walnuts",
    category: "Dry Fruits",
    price: 550,
    rating: 4.8,
    reviews: 267,
    image: "/dry-fruits-almonds-cashews-raisins.jpg",
    description: "Premium walnuts",
    details: "Premium walnuts rich in omega-3 fatty acids. Great for brain health.",
  },
  {
    id: "df6",
    name: "Pistachios",
    category: "Dry Fruits",
    price: 600,
    rating: 4.9,
    reviews: 356,
    image: "/dry-fruits-almonds-cashews-raisins.jpg",
    description: "Green pistachios",
    details: "Premium green pistachios with rich flavor. Perfect for snacking.",
  },
  {
    id: "df7",
    name: "Apricots",
    category: "Dry Fruits",
    price: 350,
    rating: 4.7,
    reviews: 198,
    image: "/black-raisins-dried.jpg",
    description: "Dried apricots",
    details: "Sweet dried apricots rich in fiber and vitamins. Great for health.",
  },
  {
    id: "df8",
    name: "Figs",
    category: "Dry Fruits",
    price: 400,
    rating: 4.6,
    reviews: 234,
    image: "/premium-dates-fruit.jpg",
    description: "Dried figs",
    details: "Premium dried figs with natural sweetness. Rich in fiber and minerals.",
  },
  {
    id: "df9",
    name: "Hazelnuts",
    category: "Dry Fruits",
    price: 520,
    rating: 4.8,
    reviews: 189,
    image: "/california-almonds-nuts.jpg",
    description: "Roasted hazelnuts",
    details: "Premium roasted hazelnuts with rich flavor. Perfect for desserts and snacking.",
  },
  {
    id: "df10",
    name: "Prunes",
    category: "Dry Fruits",
    price: 280,
    rating: 4.5,
    reviews: 156,
    image: "/black-raisins-dried.jpg",
    description: "Dried prunes",
    details: "Dried prunes rich in fiber and natural sugars. Great for digestive health.",
  },

  // Chips (10 products)
  {
    id: "c1",
    name: "Potato Chips",
    category: "Chips",
    price: 40,
    rating: 4.5,
    reviews: 289,
    image: "/crispy-potato-chips.jpg",
    description: "Crispy potato chips",
    details: "Crispy potato chips made from premium potatoes fried to golden perfection.",
  },
  {
    id: "c2",
    name: "Corn Chips",
    category: "Chips",
    price: 45,
    rating: 4.6,
    reviews: 178,
    image: "/roasted-corn-chips.jpg",
    description: "Roasted corn chips",
    details: "Crunchy roasted corn chips with perfect seasoning for snacking.",
  },
  {
    id: "c3",
    name: "Prawn Chips",
    category: "Chips",
    price: 80,
    rating: 4.7,
    reviews: 234,
    image: "/spicy-prawn-chips.jpg",
    description: "Spicy prawn chips",
    details: "Spicy prawn chips loaded with seafood flavor and crispy texture.",
  },
  {
    id: "c4",
    name: "Vegetable Chips",
    category: "Chips",
    price: 50,
    rating: 4.8,
    reviews: 267,
    image: "/healthy-vegetable-chips.jpg",
    description: "Healthy vegetable chips",
    details: "Healthy mix of vegetable chips made from natural vegetables.",
  },
  {
    id: "c5",
    name: "Onion Rings",
    category: "Chips",
    price: 55,
    rating: 4.6,
    reviews: 145,
    image: "/crispy-potato-chips.jpg",
    description: "Crispy onion rings",
    details: "Crispy onion rings with perfect seasoning. Great for snacking.",
  },
  {
    id: "c6",
    name: "Banana Chips",
    category: "Chips",
    price: 60,
    rating: 4.7,
    reviews: 198,
    image: "/roasted-corn-chips.jpg",
    description: "Sweet banana chips",
    details: "Sweet and crispy banana chips. Perfect healthy snack option.",
  },
  {
    id: "c7",
    name: "Tortilla Chips",
    category: "Chips",
    price: 48,
    rating: 4.5,
    reviews: 167,
    image: "/roasted-corn-chips.jpg",
    description: "Mexican tortilla chips",
    details: "Authentic Mexican tortilla chips perfect for dips and snacking.",
  },
  {
    id: "c8",
    name: "Cheese Chips",
    category: "Chips",
    price: 65,
    rating: 4.8,
    reviews: 234,
    image: "/crispy-potato-chips.jpg",
    description: "Cheesy chips",
    details: "Delicious cheesy chips with rich flavor. Perfect for cheese lovers.",
  },
  {
    id: "c9",
    name: "Salt & Vinegar Chips",
    category: "Chips",
    price: 42,
    rating: 4.6,
    reviews: 189,
    image: "/crispy-potato-chips.jpg",
    description: "Tangy salt & vinegar",
    details: "Tangy salt and vinegar chips with perfect flavor balance.",
  },
  {
    id: "c10",
    name: "Barbecue Chips",
    category: "Chips",
    price: 45,
    rating: 4.7,
    reviews: 256,
    image: "/spicy-prawn-chips.jpg",
    description: "Smoky barbecue flavor",
    details: "Smoky barbecue flavored chips with rich taste. Perfect for parties.",
  },

  // Biscuits (10 products)
  {
    id: "bi1",
    name: "Digestive Biscuits",
    category: "Biscuits",
    price: 60,
    rating: 4.6,
    reviews: 345,
    image: "/whole-wheat-digestive-biscuits.jpg",
    description: "Whole wheat digestive",
    details: "Nutritious digestive biscuits made from whole wheat flour and oats.",
  },
  {
    id: "bi2",
    name: "Marie Biscuits",
    category: "Biscuits",
    price: 50,
    rating: 4.5,
    reviews: 267,
    image: "/light-crispy-marie-biscuits.jpg",
    description: "Light and crispy",
    details: "Light and crispy marie biscuits perfect with tea or coffee.",
  },
  {
    id: "bi3",
    name: "Chocolate Biscuits",
    category: "Biscuits",
    price: 70,
    rating: 4.7,
    reviews: 412,
    image: "/chocolate-biscuits.jpg",
    description: "Chocolate biscuits",
    details: "Delicious chocolate-filled biscuits for chocolate lovers.",
  },
  {
    id: "bi4",
    name: "Wafer Biscuits",
    category: "Biscuits",
    price: 65,
    rating: 4.6,
    reviews: 289,
    image: "/wafer-biscuits.jpg",
    description: "Thin wafer biscuits",
    details: "Crispy wafer cookies with light and airy texture.",
  },
  {
    id: "bi5",
    name: "Butter Cookies",
    category: "Biscuits",
    price: 75,
    rating: 4.8,
    reviews: 234,
    image: "/chocolate-biscuits.jpg",
    description: "Buttery cookies",
    details: "Rich buttery cookies with melt-in-mouth texture. Perfect for tea time.",
  },
  {
    id: "bi6",
    name: "Cream Biscuits",
    category: "Biscuits",
    price: 68,
    rating: 4.7,
    reviews: 198,
    image: "/whole-wheat-digestive-biscuits.jpg",
    description: "Cream filled biscuits",
    details: "Delicious cream filled biscuits with sweet cream center.",
  },
  {
    id: "bi7",
    name: "Oreo Biscuits",
    category: "Biscuits",
    price: 80,
    rating: 4.9,
    reviews: 456,
    image: "/chocolate-biscuits.jpg",
    description: "Chocolate cream cookies",
    details: "Classic chocolate cream cookies loved by all ages.",
  },
  {
    id: "bi8",
    name: "Coconut Biscuits",
    category: "Biscuits",
    price: 62,
    rating: 4.6,
    reviews: 178,
    image: "/light-crispy-marie-biscuits.jpg",
    description: "Coconut flavored",
    details: "Coconut flavored biscuits with tropical taste. Perfect for coconut lovers.",
  },
  {
    id: "bi9",
    name: "Glucose Biscuits",
    category: "Biscuits",
    price: 45,
    rating: 4.5,
    reviews: 234,
    image: "/whole-wheat-digestive-biscuits.jpg",
    description: "Energy biscuits",
    details: "Glucose biscuits perfect for quick energy boost. Great for kids.",
  },
  {
    id: "bi10",
    name: "Honey Biscuits",
    category: "Biscuits",
    price: 58,
    rating: 4.7,
    reviews: 189,
    image: "/wafer-biscuits.jpg",
    description: "Honey sweetened",
    details: "Honey sweetened biscuits with natural sweetness. Healthy snack option.",
  },

  // Soaps (10 products)
  {
    id: "so1",
    name: "Natural Soap Bar",
    category: "Soaps",
    price: 80,
    rating: 4.6,
    reviews: 178,
    image: "/natural-soap-bar.jpg",
    description: "Natural soap bar",
    details: "Natural herbal soap bar made from organic ingredients. Gentle on skin.",
  },
  {
    id: "so2",
    name: "Herbal Shampoo",
    category: "Soaps",
    price: 150,
    rating: 4.7,
    reviews: 245,
    image: "/herbal-shampoo.jpg",
    description: "Herbal shampoo",
    details: "Herbal shampoo suitable for all hair types with natural conditioning properties.",
  },
  {
    id: "so3",
    name: "Body Wash",
    category: "Soaps",
    price: 120,
    rating: 4.5,
    reviews: 267,
    image: "/body-wash.jpg",
    description: "Gentle body wash",
    details: "Moisturizing body wash with natural oils and nourishing ingredients.",
  },
  {
    id: "so4",
    name: "Hand Wash",
    category: "Soaps",
    price: 100,
    rating: 4.8,
    reviews: 334,
    image: "/hand-wash.jpg",
    description: "Antibacterial hand wash",
    details: "Effective antibacterial handwash that keeps hands clean and fresh.",
  },
  {
    id: "so5",
    name: "Face Wash",
    category: "Soaps",
    price: 130,
    rating: 4.7,
    reviews: 198,
    image: "/natural-soap-bar.jpg",
    description: "Gentle face wash",
    details: "Gentle face wash suitable for all skin types. Keeps skin clean and fresh.",
  },
  {
    id: "so6",
    name: "Conditioner",
    category: "Soaps",
    price: 140,
    rating: 4.6,
    reviews: 234,
    image: "/herbal-shampoo.jpg",
    description: "Hair conditioner",
    details: "Nourishing hair conditioner for soft and smooth hair.",
  },
  {
    id: "so7",
    name: "Liquid Soap",
    category: "Soaps",
    price: 90,
    rating: 4.5,
    reviews: 167,
    image: "/hand-wash.jpg",
    description: "Liquid hand soap",
    details: "Liquid hand soap with moisturizing properties. Gentle on hands.",
  },
  {
    id: "so8",
    name: "Shower Gel",
    category: "Soaps",
    price: 110,
    rating: 4.6,
    reviews: 189,
    image: "/body-wash.jpg",
    description: "Refreshing shower gel",
    details: "Refreshing shower gel with pleasant fragrance. Perfect for daily use.",
  },
  {
    id: "so9",
    name: "Baby Soap",
    category: "Soaps",
    price: 70,
    rating: 4.8,
    reviews: 312,
    image: "/natural-soap-bar.jpg",
    description: "Gentle baby soap",
    details: "Gentle baby soap made with natural ingredients. Safe for sensitive baby skin.",
  },
  {
    id: "so10",
    name: "Antiseptic Soap",
    category: "Soaps",
    price: 85,
    rating: 4.7,
    reviews: 256,
    image: "/natural-soap-bar.jpg",
    description: "Antiseptic soap bar",
    details: "Antiseptic soap bar that kills germs and keeps you protected.",
  },

  // Namkeen (10 products)
  {
    id: "n1",
    name: "Bhujia",
    category: "Namkeen",
    price: 60,
    rating: 4.7,
    reviews: 289,
    image: "/bhujia-snack.jpg",
    description: "Spicy bhujia",
    details: "Traditional crispy bhujia snack made from gram flour and spices.",
  },
  {
    id: "n2",
    name: "Mathri",
    category: "Namkeen",
    price: 70,
    rating: 4.6,
    reviews: 234,
    image: "/mathri-snack.jpg",
    description: "Crispy mathri",
    details: "Crispy mathri crackers made from traditional recipe with perfect seasoning.",
  },
  {
    id: "n3",
    name: "Chakli",
    category: "Namkeen",
    price: 80,
    rating: 4.8,
    reviews: 267,
    image: "/chakli-snack.jpg",
    description: "Twisted chakli",
    details: "Traditional spiral chakli snack with perfect crunch and flavor.",
  },
  {
    id: "n4",
    name: "Sev",
    category: "Namkeen",
    price: 65,
    rating: 4.5,
    reviews: 212,
    image: "/sev-snack.jpg",
    description: "Delicious sev",
    details: "Crispy sev noodles made from gram flour with traditional Indian spices.",
  },
  {
    id: "n5",
    name: "Namkeen Mix",
    category: "Namkeen",
    price: 75,
    rating: 4.8,
    reviews: 356,
    image: "/indian-namkeen-snacks-mix.jpg",
    description: "Mixed namkeen",
    details: "Delicious mix of various namkeen snacks. Perfect for parties and snacking.",
  },
  {
    id: "n6",
    name: "Kachori",
    category: "Namkeen",
    price: 85,
    rating: 4.7,
    reviews: 198,
    image: "/mathri-snack.jpg",
    description: "Spicy kachori",
    details: "Spicy kachori with flavorful filling. Perfect Indian snack.",
  },
  {
    id: "n7",
    name: "Farsan",
    category: "Namkeen",
    price: 68,
    rating: 4.6,
    reviews: 234,
    image: "/indian-namkeen-snacks-mix.jpg",
    description: "Gujarati farsan",
    details: "Traditional Gujarati farsan with mix of crispy snacks.",
  },
  {
    id: "n8",
    name: "Mixture",
    category: "Namkeen",
    price: 72,
    rating: 4.7,
    reviews: 267,
    image: "/indian-namkeen-snacks-mix.jpg",
    description: "Crispy mixture",
    details: "Crispy mixture of various namkeen items. Perfect for tea time.",
  },
  {
    id: "n9",
    name: "Khatta Meetha",
    category: "Namkeen",
    price: 78,
    rating: 4.8,
    reviews: 189,
    image: "/bhujia-snack.jpg",
    description: "Sweet and sour",
    details: "Khatta meetha namkeen with perfect balance of sweet and sour flavors.",
  },
  {
    id: "n10",
    name: "Masala Peanuts",
    category: "Namkeen",
    price: 55,
    rating: 4.6,
    reviews: 312,
    image: "/indian-namkeen-snacks-mix.jpg",
    description: "Spicy peanuts",
    details: "Spicy masala peanuts with rich flavor. Great for snacking.",
  },
]

export default function ProductDetailPage() {
  const params = useParams()
  const productId = params.id as string
  const product = allProducts.find((p) => p.id === productId)
  const { t } = useLanguage()

  const [quantity, setQuantity] = useState(1)

  const productNameMap: Record<string, string> = {
    // Vegetables
    "Fresh Tomato": "product.fresh_tomato",
    "Golden Onion": "product.golden_onion",
    "Fresh Spinach": "product.fresh_spinach",
    "Orange Carrot": "product.orange_carrot",
    "Green Capsicum": "product.green_capsicum",
    "Fresh Garlic": "product.garlic",
    "Green Beans": "product.green_beans",
    "Cauliflower": "product.cauliflower",
    "Broccoli": "product.broccoli",
    "Potato": "product.potato",
    // Fruits
    "Fresh Red Apple": "product.fresh_red_apple",
    "Yellow Bananas": "product.yellow_bananas",
    "Orange": "product.fresh_orange",
    "Ripe Mango": "product.ripe_mango",
    "Fresh Grapes": "product.fresh_grapes",
    "Watermelon": "product.watermelon",
    "Pomegranate": "product.pomegranate",
    "Papaya": "product.papaya",
    "Guava": "product.guava",
    "Pineapple": "product.pineapple",
    // Spices
    "Turmeric Powder": "product.turmeric_powder",
    "Cumin Seeds": "product.cumin_seeds",
    "Chili Powder": "product.red_chili_powder",
    "Coriander": "product.coriander_powder",
    "Garam Masala": "product.garam_masala",
    "Black Pepper": "product.black_pepper",
    "Cardamom": "product.cardamom",
    "Cinnamon": "product.cinnamon",
    "Fenugreek Seeds": "product.fenugreek_seeds",
    "Mustard Seeds": "product.mustard_seeds",
    // Dairy
    "Fresh Milk": "product.fresh_milk",
    "Yogurt": "product.greek_yogurt",
    "Cheese Block": "product.cheddar_cheese",
    "Butter": "product.butter",
    "Paneer": "product.paneer",
    "Cream": "product.cream",
    "Ghee": "product.ghee",
    "Curd": "product.curd",
    "Mozzarella Cheese": "product.mozzarella_cheese",
    "Cottage Cheese": "product.cottage_cheese",
    // Beverages
    "Orange Juice": "product.orange_juice",
    "Premium Tea": "product.premium_tea",
    "Coffee Beans": "product.coffee_beans",
    "Mineral Water": "product.mineral_water",
    "Apple Juice": "product.apple_juice",
    "Green Tea": "product.green_tea",
    "Instant Coffee": "product.instant_coffee",
    "Coconut Water": "product.coconut_water",
    "Lemonade": "product.lemonade",
    "Herbal Tea": "product.herbal_tea",
    // Dry Fruits
    "California Almonds": "product.california_almonds",
    "Cashew Nuts": "product.cashew_nuts",
    "Black Raisins": "product.black_raisins",
    "Premium Dates": "product.dates_pack",
    "Walnuts": "product.walnuts",
    "Pistachios": "product.pistachios",
    "Apricots": "product.apricots",
    "Figs": "product.figs",
    "Hazelnuts": "product.hazelnuts",
    "Prunes": "product.prunes",
    // Chips
    "Potato Chips": "product.potato_chips",
    "Corn Chips": "product.corn_chips",
    "Prawn Chips": "product.prawn_chips",
    "Vegetable Chips": "product.vegetable_chips",
    "Onion Rings": "product.onion_rings",
    "Banana Chips": "product.banana_chips",
    "Tortilla Chips": "product.tortilla_chips",
    "Cheese Chips": "product.cheese_chips",
    "Salt & Vinegar Chips": "product.salt_vinegar_chips",
    "Barbecue Chips": "product.barbecue_chips",
    // Biscuits
    "Digestive Biscuits": "product.digestive_biscuits",
    "Marie Biscuits": "product.marie_biscuits",
    "Chocolate Biscuits": "product.chocolate_biscuits",
    "Wafer Biscuits": "product.wafer_biscuits",
    "Butter Cookies": "product.butter_cookies",
    "Cream Biscuits": "product.cream_biscuits",
    "Oreo Biscuits": "product.oreo_biscuits",
    "Coconut Biscuits": "product.coconut_biscuits",
    "Glucose Biscuits": "product.glucose_biscuits",
    "Honey Biscuits": "product.honey_biscuits",
    // Soaps
    "Natural Soap Bar": "product.natural_soap_bar",
    "Herbal Shampoo": "product.herbal_shampoo",
    "Body Wash": "product.body_wash",
    "Hand Wash": "product.hand_wash",
    "Face Wash": "product.face_wash",
    "Conditioner": "product.conditioner",
    "Liquid Soap": "product.liquid_soap",
    "Shower Gel": "product.shower_gel",
    "Baby Soap": "product.baby_soap",
    "Antiseptic Soap": "product.antiseptic_soap",
    // Namkeen
    "Bhujia": "product.bhujia",
    "Mathri": "product.mathri",
    "Chakli": "product.chakli",
    "Sev": "product.sev",
    "Namkeen Mix": "product.namkeen_mix",
    "Kachori": "product.kachori",
    "Farsan": "product.farsan",
    "Mixture": "product.mixture",
    "Khatta Meetha": "product.khatta_meetha",
    "Masala Peanuts": "product.masala_peanuts",
  }

  const getProductName = (name: string) => {
    const key = productNameMap[name]
    if (!key) return name
    const translated = t(key)
    // If translation returns the key itself (meaning translation doesn't exist), return original name
    return translated === key ? name : translated
  }

  if (!product) {
    return (
      <PageLayout>
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-foreground mb-4">Product not found</h1>
          <Link href="/shop" className="text-primary hover:underline">
            Back to Shop
          </Link>
        </div>
      </div>
      </PageLayout>
    )
  }

  return (
    <PageLayout>
    <div className="min-h-screen bg-background">
      <div className="max-w-6xl mx-auto px-4 py-8">
        <Link href="/shop" className="flex items-center gap-2 text-primary hover:underline mb-8 animate-slideInLeft">
          <ArrowLeft className="w-5 h-5" />
          Back to Shop
        </Link>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
          {/* Product Image */}
          <div className="animate-slideInLeft">
            <div className="bg-card border border-border rounded-lg overflow-hidden p-8">
              <img
                src={product.image || "/placeholder.svg"}
                alt={getProductName(product.name)}
                className="w-full h-96 object-cover rounded-lg"
              />
            </div>
          </div>

          {/* Product Details */}
          <div className="animate-slideInRight">
            <div className="space-y-6">
              <div>
                <p className="text-muted-foreground text-sm mb-2">{product.category}</p>
                <h1 className="text-4xl font-bold text-primary mb-4">{getProductName(product.name)}</h1>
                <div className="flex items-center gap-4 mb-4">
                  <div className="flex items-center gap-2">
                    <Star className="w-5 h-5 text-yellow-500 fill-yellow-500" />
                    <span className="font-bold text-foreground">{product.rating}</span>
                    <span className="text-muted-foreground">({product.reviews} reviews)</span>
                  </div>
                </div>
              </div>

              <div className="bg-card border border-border rounded-lg p-6">
                <p className="text-2xl font-bold text-primary mb-2">€{product.price}</p>
                <p className="text-foreground">{product.description}</p>
              </div>

              <div className="bg-card border border-border rounded-lg p-6">
                <h3 className="text-lg font-bold text-primary mb-4">Product Details</h3>
                <p className="text-foreground leading-relaxed">{product.details}</p>
              </div>

              <div className="flex items-center gap-4">
                <div className="flex items-center gap-3 bg-card border border-border rounded-lg p-3">
                  <button
                    onClick={() => setQuantity(Math.max(1, quantity - 1))}
                    className="px-4 py-2 hover:bg-background rounded transition-colors"
                  >
                    −
                  </button>
                  <span className="text-lg font-bold text-foreground w-8 text-center">{quantity}</span>
                  <button
                    onClick={() => setQuantity(quantity + 1)}
                    className="px-4 py-2 hover:bg-background rounded transition-colors"
                  >
                    +
                  </button>
                </div>
                <button className="flex-1 py-3 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-all duration-200 font-semibold flex items-center justify-center gap-2">
                  <ShoppingCart className="w-5 h-5" />
                  Add to Cart
                </button>
              </div>

              <div className="bg-primary/10 border border-primary/50 rounded-lg p-4 text-primary">
                <p className="text-sm font-semibold">Free Delivery on orders above €500</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </PageLayout>
  )
}
